import { IMonacoRange, IMonacoCompletionItem, MonacoCompletionItemKind, MonacoCompletionItemInsertTextRule } from "../../../gravitee-monaco-wrapper/monaco-facade";

export const latestApisSuggestions = (range: IMonacoRange, needsOpeningTag: boolean = false): IMonacoCompletionItem[] => {
  const prefix = needsOpeningTag ? '<' : '';
  const suffix = needsOpeningTag ? '>' : '';

  return [
    // Individual attribute suggestions
    {
      label: 'latest-apis:title',
      insertText: 'title="${1:Discover the latest APIs}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs title attribute',
      documentation: 'Sets the title displayed in the component header',
    },
    {
      label: 'latest-apis:subtitle',
      insertText: 'subtitle="${1:Subtitle text}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs subtitle attribute',
      documentation: 'Sets the subtitle displayed below the title',
    },
    {
      label: 'latest-apis:maxApis',
      insertText: 'maxApis="${1:5}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs max APIs attribute',
      documentation: 'Sets the maximum number of APIs to display',
    },
    {
      label: 'latest-apis:category',
      insertText: 'category="${1:all}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs category attribute',
      documentation: 'Filters APIs by category (all, featured, etc.)',
    },
    {
      label: 'latest-apis:searchQuery',
      insertText: 'searchQuery="${1:search term}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs search query attribute',
      documentation: 'Filters APIs by search query',
    },
    {
      label: 'latest-apis:cardElevation',
      insertText: 'cardElevation="${1|0,1,2,3,4,5|}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs card elevation attribute',
      documentation: 'Sets the shadow elevation for API cards (0-5)',
    },
    {
      label: 'latest-apis:cardBackgroundColor',
      insertText: 'cardBackgroundColor="${1:#ffffff}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs card background color',
      documentation: 'Sets the background color for API cards (CSS color value)',
    },
    {
      label: 'latest-apis:cardBorderRadius',
      insertText: 'cardBorderRadius="${1:8px}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs card border radius',
      documentation: 'Sets the border radius for API cards (CSS length value)',
    },
    {
      label: 'latest-apis:actionButtonText',
      insertText: 'actionButtonText="${1:View Details}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs action button text',
      documentation: 'Sets the text for action buttons',
    },
    {
      label: 'latest-apis:actionButtonVariant',
      insertText: 'actionButtonVariant="${1|filled,outlined,text|}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs action button variant',
      documentation: 'Sets the button style variant (filled, outlined, text)',
    },
    {
      label: 'latest-apis:actionButtonType',
      insertText: 'actionButtonType="${1|internal,external|}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs action button type',
      documentation: 'Sets the link type (internal: same tab, external: new tab)',
    },
    // Existing snippets with improved documentation
    {
      label: 'latest-apis',
      insertText: prefix + 'app-latest-apis' + suffix + (needsOpeningTag ? '</app-latest-apis>' : ''),
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Latest APIs component',
      documentation: 'Displays a grid of latest APIs with cards and action buttons\n\nAvailable attributes:\n• title: Component title\n• subtitle: Component subtitle\n• maxApis: Maximum number of APIs\n• category: API category filter\n• searchQuery: Search query filter\n• cardElevation: Card shadow (0-5)\n• cardBackgroundColor: Card background color\n• cardBorderRadius: Card border radius\n• actionButtonText: Button text\n• actionButtonVariant: Button style (filled/outlined/text)\n• actionButtonType: Link type (internal/external)',
    },
    {
      label: 'latest-apis-basic',
      insertText: prefix + 'app-latest-apis title="${1:Latest APIs}" [maxApis]="${2:5}"' + suffix + (needsOpeningTag ? '</app-latest-apis>' : ''),
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Basic latest APIs component',
      documentation: 'Creates a latest APIs component with custom title and number of APIs\n\nAvailable attributes:\n• title: Component title\n• subtitle: Component subtitle\n• maxApis: Maximum number of APIs\n• category: API category filter\n• searchQuery: Search query filter\n• cardElevation: Card shadow (0-5)\n• cardBackgroundColor: Card background color\n• cardBorderRadius: Card border radius\n• actionButtonText: Button text\n• actionButtonVariant: Button style (filled/outlined/text)\n• actionButtonType: Link type (internal/external)',
    },
    {
      label: 'latest-apis-featured',
      insertText: prefix + 'app-latest-apis title="${1:Featured APIs}" subtitle="${2:Discover our most popular APIs}" [maxApis]="${3:4}" category="${4:featured}"' + suffix + (needsOpeningTag ? '</app-latest-apis>' : ''),
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Featured APIs component',
      documentation: 'Creates a featured APIs component with subtitle and category filtering\n\nAvailable attributes:\n• title: Component title\n• subtitle: Component subtitle\n• maxApis: Maximum number of APIs\n• category: API category filter\n• searchQuery: Search query filter\n• cardElevation: Card shadow (0-5)\n• cardBackgroundColor: Card background color\n• cardBorderRadius: Card border radius\n• actionButtonText: Button text\n• actionButtonVariant: Button style (filled/outlined/text)\n• actionButtonType: Link type (internal/external)',
    },
    {
      label: 'latest-apis-search',
      insertText: prefix + 'app-latest-apis title="${1:Search Results}" searchQuery="${2:payment}" [maxApis]="${3:6}" actionButtonText="${4:View API}"' + suffix + (needsOpeningTag ? '</app-latest-apis>' : ''),
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Search results APIs component',
      documentation: 'Creates a search results component with query filtering and custom button text\n\nAvailable attributes:\n• title: Component title\n• subtitle: Component subtitle\n• maxApis: Maximum number of APIs\n• category: API category filter\n• searchQuery: Search query filter\n• cardElevation: Card shadow (0-5)\n• cardBackgroundColor: Card background color\n• cardBorderRadius: Card border radius\n• actionButtonText: Button text\n• actionButtonVariant: Button style (filled/outlined/text)\n• actionButtonType: Link type (internal/external)',
    },
    {
      label: 'latest-apis-custom-styled',
      insertText: prefix + 'app-latest-apis title="${1:Custom APIs}" [cardElevation]="${2:3}" cardBackgroundColor="${3:#f8f9fa}" actionButtonVariant="${4:outlined}" actionButtonText="${5:Explore API}"' + suffix + (needsOpeningTag ? '</app-latest-apis>' : ''),
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Custom styled latest APIs component',
      documentation: 'Creates a latest APIs component with custom card styling and button appearance\n\nAvailable attributes:\n• title: Component title\n• subtitle: Component subtitle\n• maxApis: Maximum number of APIs\n• category: API category filter\n• searchQuery: Search query filter\n• cardElevation: Card shadow (0-5)\n• cardBackgroundColor: Card background color\n• cardBorderRadius: Card border radius\n• actionButtonText: Button text\n• actionButtonVariant: Button style (filled/outlined/text)\n• actionButtonType: Link type (internal/external)',
    },
    {
      label: 'latest-apis-external-links',
      insertText: prefix + 'app-latest-apis title="${1:External APIs}" actionButtonType="${2:external}" actionButtonText="${3:Visit API}" [maxApis]="${4:3}"' + suffix + (needsOpeningTag ? '</app-latest-apis>' : ''),
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'External links latest APIs component',
      documentation: 'Creates a latest APIs component with external link buttons that open in new tabs\n\nAvailable attributes:\n• title: Component title\n• subtitle: Component subtitle\n• maxApis: Maximum number of APIs\n• category: API category filter\n• searchQuery: Search query filter\n• cardElevation: Card shadow (0-5)\n• cardBackgroundColor: Card background color\n• cardBorderRadius: Card border radius\n• actionButtonText: Button text\n• actionButtonVariant: Button style (filled/outlined/text)\n• actionButtonType: Link type (internal/external)',
    },
    {
      label: 'latest-apis-minimal',
      insertText: prefix + 'app-latest-apis [maxApis]="${1:3}" [cardElevation]="${2:0}" actionButtonVariant="${3:text}"' + suffix + (needsOpeningTag ? '</app-latest-apis>' : ''),
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Minimal latest APIs component',
      documentation: 'Creates a minimal latest APIs component with no elevation and text buttons\n\nAvailable attributes:\n• title: Component title\n• subtitle: Component subtitle\n• maxApis: Maximum number of APIs\n• category: API category filter\n• searchQuery: Search query filter\n• cardElevation: Card shadow (0-5)\n• cardBackgroundColor: Card background color\n• cardBorderRadius: Card border radius\n• actionButtonText: Button text\n• actionButtonVariant: Button style (filled/outlined/text)\n• actionButtonType: Link type (internal/external)',
    },
  ];
}; 