{
 "title": "APIM performances / Webhook",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "k6_rate_interval", "query": "10s" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Webhook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Webhook http duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(http_server_response_time_seconds_sum{application=\"webhook-service\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\", route=\"/hook/:subscription\"}[$__rate_interval]) / rate(http_server_response_time_seconds_count{application=\"webhook-service\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\", route=\"/hook/:subscription\"}[$__rate_interval]) * 1000)",
     "legendFormat": "{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "Webhook Throughtput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{application=\"webhook-service\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]))",
     "legendFormat": "throughtput"
    }
   ]
  },
  {
   "title": "Webhook active requests & connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_server_active_requests{application=\"webhook-service\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "req."
    },
    {
     "expr": "http_server_active_connections{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "conn."
    }
   ]
  },
  {
   "title": "Webhook bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " rate(http_server_request_bytes_sum{application=\"webhook-service\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook system cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Webhook load avg 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "Load Avg 1m"
    },
    {
     "expr": "system_cpu_count{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "CPU count"
    }
   ]
  },
  {
   "title": "Global Message Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "global_message_latency_millisecond{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{subscription}}/{{quantile}}"
    }
   ]
  },
  {
   "title": "Webhook JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Webhook jvm cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "process cpu usage"
    }
   ]
  },
  {
   "title": "Webhook jvm total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Webhook Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "heap usage"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "max heap"
    }
   ]
  },
  {
   "title": "Webhook jvm gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"webhook-service\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "K6 metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "k6 iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "iter/s" } },
   "targets": [
    {
     "expr": "rate(k6_iterations_total{scenario=\"default\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$k6_rate_interval])",
     "legendFormat": "scenario {{scenario}}"
    }
   ]
  },
  {
   "title": "k6 virtual users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "vus" } },
   "targets": [
    {
     "expr": "k6_vus{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "current vus"
    }
   ]
  },
  {
   "title": "Failure trend",
   "type": "timeseries",
   "description": "Number of failure over time",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_http_reqs_total{expected_response=\"false\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "k6_kafka_writer_error_count_total{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "k6 kafka write duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(k6_kafka_writer_write_seconds_avg{scenario=\"default\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(k6_kafka_writer_write_seconds_p90{scenario=\"default\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "max(k6_kafka_writer_write_seconds_p95{scenario=\"default\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "max(k6_kafka_writer_write_seconds_p99{scenario=\"default\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "k6 kafka bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(k6_kafka_writer_message_bytes_total{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "scenario {{scenario}}"
    }
   ]
  },
  {
   "title": "k6 kafka writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{scenario=\"default\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$k6_rate_interval]))",
     "legendFormat": "Http {{status}}"
    },
    {
     "expr": "rate(k6_kafka_writer_message_count_total{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway jvm cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Gateway system cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "system cpu"
    }
   ]
  },
  {
   "title": "Gateway system load average 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "current cpu load"
    },
    {
     "expr": "system_cpu_count{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "max cpu load"
    }
   ]
  },
  {
   "title": "Gateway heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"gio-apim-gateway\", area=\"heap\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "current heap"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"gio-apim-gateway\", area=\"heap\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "max heap"
    }
   ]
  },
  {
   "title": "Gateway jvm memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Gateway jvm gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Gateway jvm total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "Total memory"
    }
   ]
  }
 ]
}