= Run postman collections

== Run collection locally using newman.

[source]
----
newman run postman/test/collections/[...]collection.json -e postman/env/Gravitee.io-Localhost-Environment.json --bail
----

== Arguments



|===
|Argument |Short version |Long version |Default Value |Description

|POSTMAN_DIR
|`-p`
|`--postman-dir`
|../postman
|The folder containing "test" folder. Relative to your `pwd`

|POSTMAN_ENV
|`-e`
|`--postman-env`
|localhost
|The name of the environment to use. Allow to load the environment file from postman/env/Gravitee.io-*_env_*-Environment.json

|POSTMAN_URL
|`-u`
|`--postman-health-url`
|localhost:8083/management/openapi.yaml
|The endpoint to check if environment is healthy. The script will try 10 times with an interval of 5 seconds between calls before failing. *This endpoint must return a 200 status to be successful.*
|===




== Run all the tests collections locally using shell script.

[source, shell]
----
sh scripts/tests.sh
----

or

[source, shell]
----
sh scripts/tests.sh --postman-health-url=localhost:8083/management/openapi.yaml
----


== Good practices

=== Scenarios must be auto-sufficient

Each scenario must be able to run on its own. For that, we need to create the scenario need *before* executing it, and clean data *after* execution.

You can structure your collections like this:

[source]
----
MyCollection
|-- --Prepare--
|-- Scenario name
|-- --Clean Up--
MySecondCollection
|-- SubCollection#1
    |-- --Prepare--
    |-- Scenario name
    |-- --Clean Up--
|-- SubCollection#2
    |-- --Prepare--
    |-- Scenario name
    |-- --Clean Up--
----

=== Variable scopes

As explain in link:https://learning.postman.com/docs/sending-requests/variables/#choosing-variables[Postman documentation - Choosing variables], we should prefer `Collection variables` inside collections.

We use `Environment variables` for auth and URL details.

⚠️ If you run your tests with Postman, do not forget to *clear* your environment from old variables. They will take precedence over collection variables.