/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const gatewayErrorKeys = [
  'API_KEY_INVALID',
  'API_KEY_MISSING',
  'GATEWAY_CLIENT_CONNECTION_ERROR',
  'GATEWAY_CLIENT_CONNECTION_TIMEOUT',
  'GATEWAY_INVALID_REQUEST',
  'GATEWAY_INVALID_RESPONSE',
  'GATEWAY_MISSING_SECURED_REQUEST_PLAN',
  'GATEWAY_MISSING_SECURITY_PROVIDER',
  'GATEWAY_OAUTH2_ACCESS_DENIED',
  'GATEWAY_OAUTH2_INVALID_CLIENT',
  'GATEWAY_OAUTH2_SERVER_ERROR',
  'GATEWAY_PLAN_UNRESOLVABLE',
  'GATEWAY_POLICY_INTERNAL_ERROR',
  'HTTP_SIGNATURE_INVALID_SIGNATURE',
  'JSON_INVALID_FORMAT',
  'JSON_INVALID_PAYLOAD',
  'JSON_INVALID_RESPONSE_FORMAT',
  'JSON_INVALID_RESPONSE_PAYLOAD',
  'JWT_INVALID_TOKEN',
  'JWT_MISSING_TOKEN',
  'OAUTH2_INSUFFICIENT_SCOPE',
  'OAUTH2_INVALID_ACCESS_TOKEN',
  'OAUTH2_INVALID_SERVER_RESPONSE',
  'OAUTH2_MISSING_ACCESS_TOKEN',
  'OAUTH2_MISSING_HEADER',
  'OAUTH2_MISSING_SERVER',
  'OAUTH2_SERVER_UNAVAILABLE',
  'QUOTA_TOO_MANY_REQUESTS',
  'RATE_LIMIT_TOO_MANY_REQUESTS',
  'RBAC_FORBIDDEN',
  'RBAC_INVALID_USER_ROLES',
  'RBAC_NO_USER_ROLE',
  'REQUEST_CONTENT_LIMIT_LENGTH_REQUIRED',
  'REQUEST_CONTENT_LIMIT_TOO_LARGE',
  'REQUEST_TIMEOUT',
  'REQUEST_VALIDATION_INVALID',
  'RESOURCE_FILTERING_FORBIDDEN',
  'RESOURCE_FILTERING_METHOD_NOT_ALLOWED',
  'SPIKE_ARREST_TOO_MANY_REQUESTS',
  'FAILURE_ENDPOINT_CONNECTION_FAILED',
  'FAILURE_ENDPOINT_CONNECTION_CLOSED',
  'FAILURE_ENDPOINT_CONFIGURATION_INVALID',
  'FAILURE_ENDPOINT_UNKNOWN_ERROR',
  'FAILURE_ENDPOINT_PUBLISH_FAILED',
  'FAILURE_ENDPOINT_SUBSCRIBE_FAILED',
  'CLIENT_ABORTED_DURING_RESPONSE_ERROR',
] as const;
