{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus3}", "doc-type": "authz", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "authz-api-001", "event-id": "evt-001", "status": "success", "operation": "evaluate", "caller": "pep", "target-pdp-id": "default", "policy-generation": 7, "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-1", "decision": "PERMIT", "matched-policies": [{ "id": "pol-1", "name": "allow-readers", "effect": "PERMIT" }], "reasons": ["Matched policy allow-readers"], "duration-nanos": 120000 }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus2}", "doc-type": "authz", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "authz-api-001", "event-id": "evt-002", "status": "success", "operation": "evaluate", "caller": "pep", "target-pdp-id": "default", "policy-generation": 7, "subject-type": "User", "subject-id": "bob", "action": "write", "resource-type": "Account", "resource-id": "acc-2", "decision": "FORBID", "matched-policies": [{ "id": "pol-2", "name": "deny-writers", "effect": "FORBID" }], "reasons": ["Matched policy deny-writers"], "duration-nanos": 240000 }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus1}", "doc-type": "authz", "gw-id": "gw-2", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "authz-api-001", "event-id": "evt-003", "status": "success", "operation": "evaluate", "caller": "authzen", "target-pdp-id": "default", "policy-generation": 7, "subject-type": "User", "subject-id": "carol", "action": "delete", "resource-type": "Account", "resource-id": "acc-3", "decision": "NOT_APPLICABLE", "matched-policies": [], "reasons": ["No applicable policy"], "duration-nanos": 90000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "doc-type": "authz", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "authz-api-001", "event-id": "evt-004", "status": "success", "operation": "evaluate", "caller": "pep", "target-pdp-id": "default", "policy-generation": 8, "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-4", "decision": "PERMIT", "matched-policies": [{ "id": "pol-1", "name": "allow-readers", "effect": "PERMIT" }], "reasons": ["Matched policy allow-readers"], "duration-nanos": 110000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "doc-type": "authz", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "authz-api-001", "event-id": "evt-005", "status": "success", "operation": "evaluate", "caller": "pep", "target-pdp-id": "default", "policy-generation": 8, "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-5", "decision": "PERMIT", "matched-policies": [{ "id": "pol-1", "name": "allow-readers", "effect": "PERMIT" }], "reasons": ["Matched policy allow-readers"], "duration-nanos": 115000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "doc-type": "authz", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "authz-api-001", "event-id": "evt-006", "status": "error", "operation": "evaluate", "caller": "pep", "target-pdp-id": "default", "policy-generation": 8, "subject-type": "User", "subject-id": "dave", "action": "read", "resource-type": "Account", "resource-id": "acc-6", "decision": "FORBID", "matched-policies": [], "reasons": ["Engine unavailable"], "error-type": "ENGINE_ERROR", "duration-nanos": 5000 }
