{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus5}", "doc-type": "decision", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "decision-api-001", "app-id": "app-1", "plan-id": "plan-1", "event-id": "dec-g-001", "phase": "RESOLVED", "decision-point-type": "guardian", "decision-point-id": "prompt-guardian", "decision-point-version": "gpt-4o-2024-11", "checkpoint": "request.prompt", "caller": "pep", "subject-type": "User", "subject-id": "alice", "actor-type": "AgentIdentity", "actor-id": "booking-agent", "action": "flight_booking", "resource-type": "MCPTool", "resource-id": "travel.flight_booking", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "safe", "reasons": ["No rule matched"], "request-id": "req-1", "trace-id": "trace-1", "status": "success", "duration-nanos": 1200000, "additional-metrics": { "keyword_agent_type": "HOSTED_DELEGATED", "double_guardian_cost": 0.5 } }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus4}", "doc-type": "decision", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "decision-api-001", "app-id": "app-1", "plan-id": "plan-1", "event-id": "dec-g-002", "phase": "RESOLVED", "decision-point-type": "guardian", "decision-point-id": "prompt-guardian", "checkpoint": "request.prompt", "caller": "pep", "subject-id": "bob", "action": "flight_booking", "resource-id": "travel.flight_booking", "outcome": "DENY", "enforced": "DENY", "verdict": "prompt-injection", "reasons": ["Matched rule prompt-injection"], "matched-rules": [{ "id": "r1", "name": "prompt-injection", "effect": "FORBID" }], "request-id": "req-2", "status": "success", "duration-nanos": 2400000 }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus3}", "doc-type": "decision", "gw-id": "gw-2", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "decision-api-001", "app-id": "app-2", "event-id": "dec-g-003", "phase": "RESOLVED", "decision-point-type": "guardian", "decision-point-id": "prompt-guardian", "checkpoint": "response.tool_calls", "caller": "pep", "subject-id": "carol", "resource-id": "travel.hotel_booking", "outcome": "INDETERMINATE", "enforced": "ALLOW", "indeterminate-cause": "TIMEOUT", "reasons": ["Guardian did not answer within 250ms"], "request-id": "req-3", "status": "error", "error-type": "TimeoutException", "duration-nanos": 250000000 }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus2}", "doc-type": "decision", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "decision-api-001", "app-id": "app-1", "event-id": "dec-g-004", "case-id": "case-g-1", "phase": "REQUESTED", "decision-point-type": "guardian", "decision-point-id": "prompt-guardian", "checkpoint": "response.tool_calls", "caller": "pep", "subject-id": "dave", "resource-id": "travel.flight_booking", "outcome": "PENDING", "enforced": "SUSPEND", "request-id": "req-4", "status": "success" }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus1}", "doc-type": "decision", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "decision-api-001", "app-id": "app-1", "event-id": "dec-g-005", "case-id": "case-g-1", "phase": "RESOLVED", "decision-point-type": "guardian", "decision-point-id": "prompt-guardian", "checkpoint": "response.tool_calls", "caller": "pep", "subject-id": "dave", "resource-id": "travel.flight_booking", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "safe", "request-id": "req-4", "status": "success", "duration-nanos": 900000, "waited-nanos": 60000000000 }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus3}", "doc-type": "decision", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "decision-api-001", "app-id": "app-1", "event-id": "dec-h-001", "case-id": "case-h-1", "phase": "RESOLVED", "decision-point-type": "human-approval", "decision-point-id": "approval-broker", "checkpoint": "response.tool_calls", "caller": "pep", "subject-id": "erin", "resource-id": "travel.flight_booking", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "approved", "required-approver": "group:finance", "decider-type": "User", "decider-id": "frank", "channel": "slack", "request-id": "req-5", "status": "success", "additional-metrics": { "double_human-approval_cost": 1.25 } }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus2}", "doc-type": "decision", "gw-id": "gw-1", "org-id": "DEFAULT", "env-id": "DEFAULT", "api-id": "decision-api-001", "app-id": "app-1", "event-id": "dec-h-002", "case-id": "case-h-2", "phase": "REQUESTED", "decision-point-type": "human-approval", "decision-point-id": "approval-broker", "checkpoint": "response.tool_calls", "caller": "pep", "subject-id": "erin", "resource-id": "travel.hotel_booking", "outcome": "PENDING", "enforced": "SUSPEND", "required-approver": "group:finance", "channel": "slack", "request-id": "req-6", "status": "success" }
