{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus3}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "evt-001", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "7", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "request-id": "req-001", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-1", "matched-rules": [{"id": "pol-1", "name": "allow-readers", "version": "2026-09-20T10:00:00Z", "effect": "PERMIT"}], "reasons": ["Matched policy allow-readers"], "duration-nanos": 120000 }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus2}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "evt-002", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "pdp-b", "decision-point-version": "7", "caller": "pep", "status": "success", "outcome": "DENY", "enforced": "DENY", "verdict": "FORBID", "request-id": "req-002", "subject-type": "User", "subject-id": "bob", "action": "write", "resource-type": "Account", "resource-id": "acc-2", "matched-rules": [{"id": "pol-2", "name": "deny-writers", "version": "2026-09-21T10:00:00Z", "effect": "FORBID"}], "reasons": ["Matched policy deny-writers"], "duration-nanos": 240000 }
{ "create" : { ${index} } }
{ "@timestamp": "${nowMinus1}", "gw-id": "gw-2", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "evt-003", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "pdp-b", "decision-point-version": "7", "caller": "authzen", "status": "success", "outcome": "INDETERMINATE", "enforced": "DENY", "verdict": "NOT_APPLICABLE", "indeterminate-cause": "NOT_APPLICABLE", "request-id": "req-003", "subject-type": "User", "subject-id": "carol", "action": "delete", "resource-type": "Account", "resource-id": "acc-3", "matched-rules": [], "reasons": ["No applicable policy"], "duration-nanos": 90000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "evt-004", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "8", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "request-id": "req-004", "batch-id": "batch-1", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-4", "matched-rules": [{"id": "pol-1", "name": "allow-readers", "version": "2026-09-20T10:00:00Z", "effect": "PERMIT"}], "reasons": ["Matched policy allow-readers"], "duration-nanos": 110000, "additional-metrics": {"int_authz_batch-index": 0, "int_authz_batch-size": 2} }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "evt-005", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "8", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "request-id": "req-004", "batch-id": "batch-1", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-5", "matched-rules": [{"id": "pol-1", "name": "allow-readers", "version": "2026-09-20T10:00:00Z", "effect": "PERMIT"}], "reasons": ["Matched policy allow-readers"], "duration-nanos": 115000, "additional-metrics": {"int_authz_batch-index": 1, "int_authz_batch-size": 2} }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "evt-006", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "8", "caller": "pep", "status": "error", "request-id": "req-006", "outcome": "INDETERMINATE", "enforced": "DENY", "indeterminate-cause": "ERROR", "subject-type": "User", "subject-id": "dave", "action": "read", "resource-type": "Account", "resource-id": "acc-6", "reasons": ["Engine unavailable"], "error-type": "ENGINE_ERROR", "duration-nanos": 5000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "guardian-001", "phase": "RESOLVED", "decision-point-type": "guardian", "decision-point-id": "prompt-guardian", "decision-point-version": "gpt-4o-2024-11", "caller": "gateway", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-1", "outcome": "DENY", "enforced": "DENY", "verdict": "FORBID", "reasons": ["Prompt injection detected"], "status": "success", "duration-nanos": 900000000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-001", "event-id": "requested-001", "phase": "REQUESTED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "8", "caller": "pep", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-7", "outcome": "PENDING", "enforced": "SUSPEND", "status": "success" }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-001", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d1", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-002", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "docs::User", "subject-id": "alice", "action": "docs::Action::\"read\"", "resource-type": "docs::Doc", "resource-id": "d1", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-003", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "DENY", "enforced": "DENY", "verdict": "FORBID", "subject-type": "Agent", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d2", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-004", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "a::b", "action": "read", "resource-type": "Doc", "resource-id": "d3", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-005", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "authzen", "status": "success", "outcome": "INDETERMINATE", "enforced": "DENY", "verdict": "NOT_APPLICABLE", "indeterminate-cause": "NOT_APPLICABLE", "subject-id": "x::y", "action": "read", "resource-id": "r::s", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-006", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "say \"hi\"", "action": "read", "resource-type": "Doc", "resource-id": "d4", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-008", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "C:\\temp", "action": "read", "resource-type": "Doc", "resource-id": "d5", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-entity-refs", "event-id": "ref-009", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "*", "action": "read", "resource-type": "Doc", "resource-id": "d6", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-scoping", "event-id": "authz-envA", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d1", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#2", "api-id": "authz-api-scoping", "event-id": "authz-envB", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d1", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#2", "env-id": "env#1", "api-id": "authz-api-scoping", "event-id": "authz-orgB", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d1", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-scoping", "event-id": "guardian-envA", "phase": "RESOLVED", "decision-point-type": "guardian", "decision-point-id": "prompt-guardian", "caller": "gateway", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "allow", "status": "success" }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-scoping", "event-id": "authz-requested", "phase": "REQUESTED", "decision-point-type": "authz", "decision-point-id": "default", "caller": "pep", "outcome": "PENDING", "enforced": "SUSPEND", "status": "success" }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-cold-start", "event-id": "cold-start-001", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "caller": "pep", "status": "error", "request-id": "req-cold-001", "outcome": "INDETERMINATE", "enforced": "DENY", "indeterminate-cause": "NOT_READY", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Account", "resource-id": "acc-1", "reasons": ["PDP not ready"], "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-uiqa", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "3", "caller": "pep", "event-id": "uiqa-001", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d1", "matched-rules": [{"id": "pol-qa", "name": "QA default#0", "version": "1", "effect": "PERMIT"}], "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-uiqa", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "3", "caller": "pep", "event-id": "uiqa-002", "status": "success", "outcome": "DENY", "enforced": "DENY", "verdict": "FORBID", "subject-type": "User", "subject-id": "alice", "action": "write", "resource-type": "Doc", "resource-id": "d1", "matched-rules": [{"id": "pol-qa", "name": "QA default#2", "version": "1", "effect": "FORBID"}], "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-uiqa", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "3", "caller": "pep", "event-id": "uiqa-003", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d2", "matched-rules": [{"id": "pol-q", "name": "QA#1", "version": "1", "effect": "PERMIT"}], "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-uiqa", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "3", "caller": "pep", "event-id": "uiqa-004", "status": "error", "outcome": "INDETERMINATE", "enforced": "DENY", "indeterminate-cause": "TIMEOUT", "error-type": "evaluation_timeout", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d3", "reasons": ["Evaluation timed out"], "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-uiqa", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "3", "caller": "pep", "event-id": "uiqa-005", "status": "error", "outcome": "INDETERMINATE", "enforced": "DENY", "indeterminate-cause": "ERROR", "error-type": "pdp_unavailable", "subject-type": "User", "subject-id": "alice", "action": "read", "resource-type": "Doc", "resource-id": "d4", "reasons": ["PDP unavailable"], "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-top-list", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "subject-type": "User", "subject-id": "alice", "resource-type": "Doc", "resource-id": "d1", "event-id": "top-list-001", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "action": "read", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-top-list", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "subject-type": "User", "subject-id": "alice", "resource-type": "Doc", "resource-id": "d1", "event-id": "top-list-002", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "action": "read", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-top-list", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "subject-type": "User", "subject-id": "alice", "resource-type": "Doc", "resource-id": "d1", "event-id": "top-list-003", "status": "success", "outcome": "ALLOW", "enforced": "ALLOW", "verdict": "PERMIT", "action": "read", "duration-nanos": 1000 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-top-list", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "subject-type": "User", "subject-id": "alice", "resource-type": "Doc", "resource-id": "d1", "event-id": "top-list-004", "status": "success", "outcome": "DENY", "enforced": "DENY", "verdict": "FORBID", "action": "write", "duration-nanos": 0 }
{ "create" : { ${index} } }
{ "@timestamp": "${now}", "gw-id": "gw-1", "org-id": "org#1", "env-id": "env#1", "api-id": "authz-api-top-list", "phase": "RESOLVED", "decision-point-type": "authz", "decision-point-id": "default", "decision-point-version": "1", "caller": "pep", "subject-type": "User", "subject-id": "alice", "resource-type": "Doc", "resource-id": "d1", "event-id": "top-list-005", "status": "error", "outcome": "INDETERMINATE", "enforced": "DENY", "indeterminate-cause": "ERROR", "error-type": "evaluation_failed", "action": "admin", "duration-nanos": 1000 }
