pull_request_rules:
    - name: Apply commits on `master`
      conditions:
          - label=apply-on-master
      actions:
          backport:
              branches:
                  - master
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[master] {{ title }}"
    - name: Apply commits on `4.5.x`
      conditions:
          - label=apply-on-4-5-x
      actions:
          backport:
              branches:
                  - 4.5.x
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[4.5.x] {{ title }}"
    - name: Apply commits on `4.4.x`
      conditions:
          - label=apply-on-4-4-x
      actions:
          backport:
              branches:
                  - 4.4.x
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[4.4.x] {{ title }}"
    - name: Apply commits on `4.3.x`
      conditions:
          - label=apply-on-4-3-x
      actions:
          backport:
              branches:
                  - 4.3.x
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[4.3.x] {{ title }}"
    - name: Apply commits on `4.2.x`
      conditions:
          - label=apply-on-4-2-x
      actions:
          backport:
              branches:
                  - 4.2.x
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[4.2.x] {{ title }}"
    - name: Apply commits on `4.1.x`
      conditions:
          - label=apply-on-4-1-x
      actions:
          backport:
              branches:
                  - 4.1.x
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[4.1.x] {{ title }}"
