pull_request_rules:
    - name: Apply commits on `master`
      conditions:
          - label=apply-on-master
      actions:
          backport:
              branches:
                  - master
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[master] {{ title }}"
    - name: Apply commits on `4.9.x`
      conditions:
        - label=apply-on-4-9-x
      actions:
        backport:
          branches:
            - 4.9.x
          assignees:
            - "{{ author }}"
          body: |
            This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

            ----

            {{ body }}

            ----
            {{ cherry_pick_error }}
          title: "[4.9.x] {{ title }}"
    - name: Apply commits on `4.8.x`
      conditions:
        - label=apply-on-4-8-x
      actions:
        backport:
          branches:
            - 4.8.x
          assignees:
            - "{{ author }}"
          body: |
            This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).
            
            ----
            
            {{ body }}
            
            ----
            {{ cherry_pick_error }}
          title: "[4.8.x] {{ title }}"
    - name: Apply commits on `4.7.x`
      conditions:
        - label=apply-on-4-7-x
      actions:
        backport:
          branches:
            - 4.7.x
          assignees:
            - "{{ author }}"
          body: |
            This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).
            
            ----
            
            {{ body }}
            
            ----
            {{ cherry_pick_error }}
          title: "[4.7.x] {{ title }}"
    - name: Apply commits on `4.6.x`
      conditions:
          - label=apply-on-4-6-x
      actions:
          backport:
              branches:
                  - 4.6.x
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[4.6.x] {{ title }}"
    - name: Apply commits on `4.5.x`
      conditions:
          - label=apply-on-4-5-x
      actions:
          backport:
              branches:
                  - 4.5.x
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[4.5.x] {{ title }}"
