
= Gravitee.io API Management

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License", link="https://github.com/gravitee-io/gravitee-api-management/blob/master/LICENSE"]
image:https://circleci.com/gh/gravitee-io/gravitee-api-management.svg?style=svg["CircleCI", link="https://circleci.com/gh/gravitee-io/gravitee-api-management"]

image:./assets/gravitee-logo-cyan.svg["Gravitee.io",400]

== Overview

Gravitee.io API Management is a flexible, lightweight and blazing-fast Open Source solution that helps your organization control who, when and how users access your APIs. Effortlessly manage the lifecycle of your APIs. Download API Management to document, discover and publish your APIs.

=== Features

- Register your API : Create and register APIs in a matter of a few clicks to easily expose your secured APIs to internal and external consumers.
- Configure policies using flows: Gravitee.io API Management provides over 50 pre-built policies to effectively shape traffic reaching the gateway according to your business requirements.
- Developer portal: Build the portal that your developers want with a custom theme, full text search and API documentation.
- Analytics dashboard: The out-of-the-box dashboards give you a 360-degree view of your API. You can also build your own dashboards from Gravitee.io or use all metrics with external tools like Grafana or Kibana.
- Register applications: Users and administrators can register applications for consuming APIs with ease. Gravitee.io provides advanced dynamic client registration to effectively link API Management and Access Management.
- Secured plan: Create contracts between your API consumers and APIs - building API products from your backend services.

== Documentation

You can find Gravitee.io API Management's documentation on https://docs.gravitee.io/[Gravitee.io website].

== Community
Got questions, suggestions or feedback? Why not join us on the https://community.gravitee.io/[community forum].
