= Gravitee Management REST API

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-management-rest-api/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-management-rest-api/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Overview

A restful API providing a bunch of services to manage and configure the global platform.
All exposed services are constraint by authentication and authorization rules.

== Documentation

You can find Gravitee.io API Management documentation from https://docs.gravitee.io/[Gravitee.io website].

== Building

```
$ git clone https://github.com/gravitee-io/gravitee-management-rest-api
$ cd gravitee-management-rest-api
$ mvn clean compile exec:java -Pdev -pl gravitee-rest-api-standalone/gravitee-rest-api-standalone-container
...
<app starts and listens on port 8083>
```

== Makefile support

You can use link:Makefile[Makefile] to set up an environment locally and run `Postman` tests against it.

Run `make` or `make --help` to see the list of available commands.

=== Build and start your environment

`make gravitee`

The version will be based on your current branch's link:pom.xml[pom.xml]

If containers exists, they will be stopped and deleted.

You can skip tests running `make gravitee OPTIONS=-DskipTests`

=== Start or stop the environment

`make start`

`make stop`

=== Reset the environment

`make reset`

Stop the containers, delete data on databases and start the containers

=== Run Postman tests

Your environment need to be up. A message will be prompted if it is not the case.

`make postman` will run postman collections on localhost.

You can specify `nightly` or `demo` parameters to choose where to run collections.

`make postman env=nightly`

`make postman env=demo`

=== Insert bulk of data

Your environment need to be up. A message will be prompted if it is not the case.

`make bulk` will insert 100 Applications and 100 Apis on localhost.
