/*
 * Copyright © 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package fixtures.core.model;

import io.gravitee.apim.core.subscription_form.model.SubscriptionForm;
import io.gravitee.apim.core.subscription_form.model.SubscriptionFormId;

/**
 * Test fixtures for SubscriptionForm.
 *
 * @author Gravitee.io Team
 */
public class SubscriptionFormFixtures {

    private SubscriptionFormFixtures() {}

    public static final String FORM_ID = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d";
    public static final String ENVIRONMENT_ID = "environment-id";
    public static final String GMD_CONTENT = "<gmd-input name=\"company\" label=\"Company\" required=\"true\"/>";

    public static SubscriptionForm aSubscriptionForm() {
        return SubscriptionForm.builder()
            .id(SubscriptionFormId.of(FORM_ID))
            .environmentId(ENVIRONMENT_ID)
            .gmdContent(GMD_CONTENT)
            .enabled(false)
            .build();
    }

    /**
     * Subscription form without id (for create flow where id is generated by CrudService).
     */
    public static SubscriptionForm aSubscriptionFormWithNullId() {
        return SubscriptionForm.builder().id(null).environmentId(ENVIRONMENT_ID).gmdContent(GMD_CONTENT).enabled(false).build();
    }

    public static SubscriptionForm anEnabledSubscriptionForm() {
        return SubscriptionForm.builder()
            .id(SubscriptionFormId.of(FORM_ID))
            .environmentId(ENVIRONMENT_ID)
            .gmdContent(GMD_CONTENT)
            .enabled(true)
            .build();
    }

    public static SubscriptionForm.SubscriptionFormBuilder aSubscriptionFormBuilder() {
        return SubscriptionForm.builder()
            .id(SubscriptionFormId.of(FORM_ID))
            .environmentId(ENVIRONMENT_ID)
            .gmdContent(GMD_CONTENT)
            .enabled(false);
    }
}
