openapi: 3.0.3
info:
    title: Gravitee.io APIM - Management API - Plugins - Deprecated
    description: |-
        This is the OpenAPI specification for our new version of APIM Management API.
    contact:
        email: team-apim@graviteesource.com
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    version: 2.0.0

security:
    - CookieAuth: []

servers:
    - url: "/management/v2"
      description: APIM Management API v2 - Default base URL

tags:
    - name: Plugins - Endpoints
      description: Everything about endpoint plugins
    - name: Plugins - Entrypoints
      description: Everything about entrypoint plugins
    - name: Plugins - Policies
      description: Everything about policies plugins

paths:
    # Plugins - Endpoints
    /plugins/endpoints:
        get:
            tags:
                - Plugins - Endpoints
            summary: Get available endpoints on the platform
            description: |
                Get available endpoint types on the platform.

                User must be authenticated.
            operationId: getEndpointsDeprecated
            deprecated: true
            responses:
                "200":
                    description: List of Endpoints.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                  $ref: "./openapi-plugins.yaml#/components/schemas/ConnectorPlugin"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/endpoints/{endpointId}:
        parameters:
            - $ref: "#/components/parameters/endpointIdParam"
        get:
            tags:
                - Plugins - Endpoints
            summary: Get an endpoint
            description: |
                Get an endpoint type.

                User must be authenticated.
            operationId: getEndpointDeprecated
            deprecated: true
            responses:
                "200":
                    description: Endpoint
                    content:
                        application/json:
                            schema:
                                $ref: "./openapi-plugins.yaml#/components/schemas/ConnectorPlugin"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/endpoints/{endpointId}/documentation:
        parameters:
            - $ref: "#/components/parameters/endpointIdParam"
        get:
            tags:
                - Plugins - Endpoints
            summary: Get an endpoint documentation
            description: |
                Get the documentation of an endpoint.

                User must be authenticated.
            operationId: getEndpointDocumentationDeprecated
            deprecated: true
            responses:
                "200":
                    description: Documentation of the endpoint
                    content:
                        text/plain:
                            schema:
                                type: string
                default:
                    $ref: "#/components/responses/Error"
    /plugins/endpoints/{endpointId}/more-information:
        parameters:
            - $ref: "#/components/parameters/endpointIdParam"
        get:
            tags:
                - Plugins - Endpoints
            summary: Get more information about how to use a given endpoint
            description: |
                More information about the endpoint.

                User must be authenticated.
            operationId: getEndpointMoreInformationDeprecated
            deprecated: true
            responses:
                "200":
                    description: More information of the endpoint
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/MoreInformation"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/endpoints/{endpointId}/schema:
        parameters:
            - $ref: "#/components/parameters/endpointIdParam"
        get:
            tags:
                - Plugins - Endpoints
            summary: Get an endpoint schema
            description: |
                Get the JSON schema that describes the configuration of an endpoint.

                User must be authenticated.
            operationId: getEndpointSchemaDeprecated
            deprecated: true
            responses:
                "200":
                    $ref: "#/components/responses/SchemaFormResponse"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/endpoints/{endpointId}/shared-configuration-schema:
        parameters:
            - $ref: "#/components/parameters/endpointIdParam"
        get:
            tags:
                - Plugins - Endpoints
            summary: Get an endpoint shared configuration schema
            description: |
                Get an endpoint shared configuration schema.

                User must be authenticated.
            operationId: getEndpointSharedConfigurationSchemaDeprecated
            deprecated: true
            responses:
                "200":
                    $ref: "#/components/responses/SchemaFormResponse"
                default:
                    $ref: "#/components/responses/Error"

    # Plugins - Entrypoints
    /plugins/entrypoints:
        get:
            tags:
                - Plugins - Entrypoints
            summary: Get available entrypoints on the platform
            description: |
                Get available entrypoint types on the platform.

                User must be authenticated.
            operationId: getEntrypointsDeprecated
            deprecated: true
            responses:
                "200":
                    description: List of Entrypoints.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "./openapi-plugins.yaml#/components/schemas/ConnectorPlugin"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/entrypoints/{entrypointId}:
        parameters:
            - $ref: "#/components/parameters/entrypointIdParam"
        get:
            tags:
                - Plugins - Entrypoints
            summary: Get an entrypoint
            description: |
                Get an entrypoint type.

                User must be authenticated.
            operationId: getEntrypointDeprecated
            deprecated: true
            responses:
                "200":
                    description: Entrypoint
                    content:
                        application/json:
                            schema:
                                $ref: "./openapi-plugins.yaml#/components/schemas/ConnectorPlugin"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/entrypoints/{entrypointId}/documentation:
        parameters:
            - $ref: "#/components/parameters/entrypointIdParam"
        get:
            tags:
                - Plugins - Entrypoints
            summary: Get an entrypoint documentation
            description: |
                Get the documentation of an entrypoint.

                User must be authenticated.
            operationId: getEntrypointDocumentationDeprecated
            deprecated: true
            responses:
                "200":
                    description: Documentation of the entrypoint
                    content:
                        text/plain:
                            schema:
                                type: string
                default:
                    $ref: "#/components/responses/Error"
    /plugins/entrypoints/{entrypointId}/more-information:
        parameters:
            - $ref: "#/components/parameters/entrypointIdParam"
        get:
            tags:
                - Plugins - Entrypoints
            summary: Get more information about how to use a given entrypoint
            description: |
                More information about the entrypoint.

                User must be authenticated.
            operationId: getEntrypointMoreInformationDeprecated
            deprecated: true
            responses:
                "200":
                    description: More information of the entrypoint
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/MoreInformation"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/entrypoints/{entrypointId}/schema:
        parameters:
            - $ref: "#/components/parameters/entrypointIdParam"
        get:
            tags:
                - Plugins - Entrypoints
            summary: Get an entrypoint schema
            description: |
                Get the JSON schema that describes the configuration of an entrypoint.

                User must be authenticated.
            operationId: getEntrypointSchemaDeprecated
            deprecated: true
            responses:
                "200":
                    $ref: "#/components/responses/SchemaFormResponse"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/entrypoints/{entrypointId}/subscription-schema:
        parameters:
            - $ref: "#/components/parameters/entrypointIdParam"
        get:
            parameters:
                - name: display
                  in: query
                  description: Display the schema in a specific format..
                  required: false
                  schema:
                      type: string
                      default: gio-form-json-schema
                      enum:
                          - gv-schema-form
                          - gio-form-json-schema
            tags:
                - Plugins - Entrypoints
            summary: Get an entrypoint subscription schema
            description: |
                Get the JSON schema that describes the subscription to a given entrypoint.

                User must be authenticated.
            operationId: getEntrypointSubscriptionSchemaDeprecated
            deprecated: true
            responses:
                "200":
                    $ref: "#/components/responses/SchemaFormResponse"
                default:
                    $ref: "#/components/responses/Error"

    # Plugins - Policies
    /plugins/policies:
        get:
            tags:
                - Plugins - Policies
            summary: Get available policies on the platform
            description: |
                Get available policies on the platform.

                User must be authenticated.
            operationId: getPoliciesDeprecated
            deprecated: true
            responses:
                "200":
                    description: List of Policies.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                   $ref: "./openapi-plugins.yaml#/components/schemas/PolicyPlugin"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/policies/{policyId}:
        parameters:
            - $ref: "#/components/parameters/policyIdParam"
        get:
            tags:
                - Plugins - Policies
            summary: Get a policy
            description: |
                Get a policy.

                User must be authenticated.
            operationId: getPolicyDeprecated
            deprecated: true
            responses:
                "200":
                    description: Policy
                    content:
                        application/json:
                            schema:
                               $ref: "./openapi-plugins.yaml#/components/schemas/PolicyPlugin"
                default:
                    $ref: "#/components/responses/Error"
    /plugins/policies/{policyId}/documentation:
        parameters:
            - $ref: "#/components/parameters/policyIdParam"
        get:
            tags:
                - Plugins - Policies
            summary: Get a policy documentation
            description: |
                Get the documentation of a policy.

                User must be authenticated.
            operationId: getPolicyDocumentationDeprecated
            deprecated: true
            responses:
                "200":
                    description: Documentation of the entrypoint
                    content:
                        text/plain:
                            schema:
                                type: string
                default:
                    $ref: "#/components/responses/Error"
    /plugins/policies/{policyId}/schema:
        parameters:
            - $ref: "#/components/parameters/policyIdParam"
        get:
            parameters:
                - name: display
                  in: query
                  description: Display the schema in a specific format..
                  required: false
                  schema:
                      type: string
                      default: gio-form-json-schema
                      enum:
                          - gv-schema-form
                          - gio-form-json-schema
            tags:
                - Plugins - Policies
            summary: Get a policy schema
            description: |
                Get the JSON schema that describes the configuration of a policy.

                User must be authenticated.
            operationId: getPolicySchemaDeprecated
            deprecated: true
            responses:
                "200":
                    $ref: "#/components/responses/SchemaFormResponse"
                default:
                    $ref: "#/components/responses/Error"

components:
    schemas:
        PlatformPlugin:
            type: object
            properties:
                id:
                    type: string
                    description: Plugin's uuid.
                    example: 00f8c9e7-78fc-4907-b8c9-e778fc790750
                name:
                    type: string
                    description: Plugin's name.
                    example: My Plugin
                    minLength: 1
                description:
                    type: string
                    description: Plugin's description.
                    example: I can use many characters to describe this plugin.
                    minLength: 1
                icon:
                    type: string
                    description: Plugin's icon.
                    minLength: 1
                category:
                    type: string
                    description: Plugin's category.
                    example: policy
                    minLength: 1
                version:
                    type: string
                    description: Plugin's version.
                    example: 1.0.0
                    minLength: 1
                deployed:
                    type: boolean
                    description: The deployment status of the plugin. This property is true if the plugin is deployed on the installation and the license allows to use it.
        MoreInformation:
            type: object
            properties:
                description:
                    type: string
                    description: Plugin's description.
                    example: Let your consumers send synchronous, on-demand requests for events via a standard HTTP GET requests. Use a standard HTTP proxy to mediate between client applications as data consumers and event brokers such as Kafka.
                documentationUrl:
                    type: string
                    description: Plugin's documentation URL.
                    example: https://documentation.gravitee.io
                schemaImg:
                    type: string
                    description: Plugin's schema image as base64.
                    format: base64
                    example: data:image/png;base64,aFDqfda
        Error:
            type: object
            properties:
                httpStatus:
                    type: integer
                    format: int32
                    description: The error code
                    example: 400
                message:
                    type: string
                    description: The error message
                    example: Bad request
                technicalCode:
                    type: string
                    description: A technical code to identify the error
                    example: invalid.import.definition
                parameters:
                    type: object
                    description: A map of parameters to be used in the error message
                    additionalProperties:
                        type: string
                details:
                    type: array
                    description: A list of details about the error
                    items:
                        type: object
                        properties:
                            message:
                                type: string
                                description: The error message
                                example: Bad request
                            location:
                                type: string
                                description: The json path of the field in error.
                                example: updateApi.properties[0].key
                            invalidValue:
                                description: The invalid value.
    parameters:
        organizationIdParam:
            name: orgId
            in: path
            required: true
            description: Id of an organization.
            schema:
                type: string
        endpointIdParam:
            name: endpointId
            in: path
            required: true
            description: Id of an endpoint.
            schema:
                type: string
        entrypointIdParam:
            name: entrypointId
            in: path
            required: true
            description: Id of an entrypoint.
            schema:
                type: string
        policyIdParam:
            name: policyId
            in: path
            required: true
            description: Id of a policy.
            schema:
                type: string
    responses:
        SchemaFormResponse:
            description: Schema form of a plugin
            content:
                application/json:
                    schema:
                        type: object
        Error:
            description: Generic error response
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"

    securitySchemes:
        CookieAuth:
            type: apiKey
            in: cookie
            name: Auth-Graviteeio-APIM
