#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG GRAVITEEIO_VERSION=0

FROM openjdk:17-slim AS jre-build
LABEL maintainer="contact@graviteesource.com"

ARG GRAVITEEIO_VERSION

ENV GRAVITEEIO_HOME /opt/graviteeio-gateway

WORKDIR ${GRAVITEEIO_HOME}

ADD ./gravitee-apim-gateway-distribution-${GRAVITEEIO_VERSION}.tar.gz /tmp

RUN jlink --verbose \
        --compress 2 \
        --strip-java-debug-attributes \
        --no-header-files \
        --no-man-pages \
        --output jre \
        --add-modules java.base,jdk.zipfs,java.naming,jdk.naming.dns,java.desktop,java.management,java.sql,jdk.unsupported,jdk.net,java.scripting,jdk.dynalink,jdk.management.agent,jdk.crypto.ec \
    && mv /tmp/gravitee-apim-gateway-distribution-${GRAVITEEIO_VERSION}/* ${GRAVITEEIO_HOME}

FROM ubuntu:focal
LABEL maintainer="contact@graviteesource.com"

ENV GRAVITEEIO_HOME /opt/graviteeio-gateway
ENV JAVA_HOME=${GRAVITEEIO_HOME}/jre

# copy the custom JRE produced from jlink
COPY --from=jre-build ${GRAVITEEIO_HOME} ${GRAVITEEIO_HOME}

RUN apt-get update \
    && apt-get --yes upgrade \
    && apt-get --yes install netcat-openbsd wget curl htop \
    && rm -rf /var/lib/apt/lists/* \
	&& chgrp -R 0 ${GRAVITEEIO_HOME} \
    && chmod -R g=u ${GRAVITEEIO_HOME}

WORKDIR ${GRAVITEEIO_HOME}
EXPOSE 8082
ENTRYPOINT ["./bin/gravitee"]
VOLUME ${GRAVITEEIO_HOME}/logs
HEALTHCHECK --interval=5s --timeout=3s --retries=6 --start-period=30s \
            CMD curl --user admin:adminadmin --fail http://localhost:18082/_node/health || exit 1
