/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiReview
 */
export interface ApiReview {
    /**
     * 
     * @type {boolean}
     * @memberof ApiReview
     */
    enabled?: boolean;
}

export function ApiReviewFromJSON(json: any): ApiReview {
    return ApiReviewFromJSONTyped(json, false);
}

export function ApiReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiReview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function ApiReviewToJSON(value?: ApiReview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}


