/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoadBalancer
 */
export interface LoadBalancer {
    /**
     * 
     * @type {string}
     * @memberof LoadBalancer
     */
    type?: LoadBalancerTypeEnum;
}

export function LoadBalancerFromJSON(json: any): LoadBalancer {
    return LoadBalancerFromJSONTyped(json, false);
}

export function LoadBalancerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadBalancer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function LoadBalancerToJSON(value?: LoadBalancer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

/**
* @export
* @enum {string}
*/
export enum LoadBalancerTypeEnum {
    ROUNDROBIN = 'ROUND_ROBIN',
    RANDOM = 'RANDOM',
    WEIGHTEDROUNDROBIN = 'WEIGHTED_ROUND_ROBIN',
    WEIGHTEDRANDOM = 'WEIGHTED_RANDOM'
}


