/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BodyPart,
    BodyPartFromJSON,
    BodyPartFromJSONTyped,
    BodyPartToJSON,
    BodyPartMediaType,
    BodyPartMediaTypeFromJSON,
    BodyPartMediaTypeFromJSONTyped,
    BodyPartMediaTypeToJSON,
    ContentDisposition,
    ContentDispositionFromJSON,
    ContentDispositionFromJSONTyped,
    ContentDispositionToJSON,
    ParameterizedHeader,
    ParameterizedHeaderFromJSON,
    ParameterizedHeaderFromJSONTyped,
    ParameterizedHeaderToJSON,
} from './';

/**
 * 
 * @export
 * @interface MultiPart
 */
export interface MultiPart {
    /**
     * 
     * @type {ContentDisposition}
     * @memberof MultiPart
     */
    contentDisposition?: ContentDisposition;
    /**
     * 
     * @type {object}
     * @memberof MultiPart
     */
    entity?: object;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof MultiPart
     */
    headers?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {BodyPartMediaType}
     * @memberof MultiPart
     */
    mediaType?: BodyPartMediaType;
    /**
     * 
     * @type {object}
     * @memberof MultiPart
     */
    messageBodyWorkers?: object;
    /**
     * 
     * @type {MultiPart}
     * @memberof MultiPart
     */
    parent?: MultiPart;
    /**
     * 
     * @type {object}
     * @memberof MultiPart
     */
    providers?: object;
    /**
     * 
     * @type {Array<BodyPart>}
     * @memberof MultiPart
     */
    bodyParts?: Array<BodyPart>;
    /**
     * 
     * @type {{ [key: string]: Array<ParameterizedHeader>; }}
     * @memberof MultiPart
     */
    parameterizedHeaders?: { [key: string]: Array<ParameterizedHeader>; };
}

export function MultiPartFromJSON(json: any): MultiPart {
    return MultiPartFromJSONTyped(json, false);
}

export function MultiPartFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPart {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentDisposition': !exists(json, 'contentDisposition') ? undefined : ContentDispositionFromJSON(json['contentDisposition']),
        'entity': !exists(json, 'entity') ? undefined : json['entity'],
        'headers': !exists(json, 'headers') ? undefined : json['headers'],
        'mediaType': !exists(json, 'mediaType') ? undefined : BodyPartMediaTypeFromJSON(json['mediaType']),
        'messageBodyWorkers': !exists(json, 'messageBodyWorkers') ? undefined : json['messageBodyWorkers'],
        'parent': !exists(json, 'parent') ? undefined : MultiPartFromJSON(json['parent']),
        'providers': !exists(json, 'providers') ? undefined : json['providers'],
        'bodyParts': !exists(json, 'bodyParts') ? undefined : ((json['bodyParts'] as Array<any>).map(BodyPartFromJSON)),
        'parameterizedHeaders': !exists(json, 'parameterizedHeaders') ? undefined : json['parameterizedHeaders'],
    };
}

export function MultiPartToJSON(value?: MultiPart | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentDisposition': ContentDispositionToJSON(value.contentDisposition),
        'entity': value.entity,
        'headers': value.headers,
        'mediaType': BodyPartMediaTypeToJSON(value.mediaType),
        'messageBodyWorkers': value.messageBodyWorkers,
        'parent': MultiPartToJSON(value.parent),
        'providers': value.providers,
        'bodyParts': value.bodyParts === undefined ? undefined : ((value.bodyParts as Array<any>).map(BodyPartToJSON)),
        'parameterizedHeaders': value.parameterizedHeaders,
    };
}


