/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AlertTimeUnit,
    AlertTimeUnitFromJSON,
    AlertTimeUnitFromJSONTyped,
    AlertTimeUnitToJSON,
    AlertType,
    AlertTypeFromJSON,
    AlertTypeFromJSONTyped,
    AlertTypeToJSON,
    AlertWebhook,
    AlertWebhookFromJSON,
    AlertWebhookFromJSONTyped,
    AlertWebhookToJSON,
} from './';

/**
 * 
 * @export
 * @interface Alert
 */
export interface Alert {
    /**
     * Unique identifier of an alert.
     * @type {string}
     * @memberof Alert
     */
    id?: string;
    /**
     * true, if alert is enabled
     * @type {boolean}
     * @memberof Alert
     */
    enabled?: boolean;
    /**
     * 
     * @type {AlertType}
     * @memberof Alert
     */
    type?: AlertType;
    /**
     * Filter on API id (empty for all apis)
     * @type {string}
     * @memberof Alert
     */
    api?: string;
    /**
     * Alert description
     * @type {string}
     * @memberof Alert
     */
    description?: string;
    /**
     * Http status code to trigger the alert
     * @type {string}
     * @memberof Alert
     */
    status_code?: string;
    /**
     * Percent to trigger the alert on status code
     * @type {number}
     * @memberof Alert
     */
    status_percent?: number;
    /**
     * Response time to trigger the alert
     * @type {number}
     * @memberof Alert
     */
    response_time?: number;
    /**
     * Compute alert on selected duration
     * @type {number}
     * @memberof Alert
     */
    duration?: number;
    /**
     * 
     * @type {AlertTimeUnit}
     * @memberof Alert
     */
    time_unit?: AlertTimeUnit;
    /**
     * 
     * @type {AlertWebhook}
     * @memberof Alert
     */
    webhook?: AlertWebhook;
}

export function AlertFromJSON(json: any): Alert {
    return AlertFromJSONTyped(json, false);
}

export function AlertFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alert {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'type': !exists(json, 'type') ? undefined : AlertTypeFromJSON(json['type']),
        'api': !exists(json, 'api') ? undefined : json['api'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status_code': !exists(json, 'status_code') ? undefined : json['status_code'],
        'status_percent': !exists(json, 'status_percent') ? undefined : json['status_percent'],
        'response_time': !exists(json, 'response_time') ? undefined : json['response_time'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'time_unit': !exists(json, 'time_unit') ? undefined : AlertTimeUnitFromJSON(json['time_unit']),
        'webhook': !exists(json, 'webhook') ? undefined : AlertWebhookFromJSON(json['webhook']),
    };
}

export function AlertToJSON(value?: Alert | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'enabled': value.enabled,
        'type': AlertTypeToJSON(value.type),
        'api': value.api,
        'description': value.description,
        'status_code': value.status_code,
        'status_percent': value.status_percent,
        'response_time': value.response_time,
        'duration': value.duration,
        'time_unit': AlertTimeUnitToJSON(value.time_unit),
        'webhook': AlertWebhookToJSON(value.webhook),
    };
}


