/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInput
 */
export interface UserInput {
    /**
     * Unique identifier of a user.
     * @type {string}
     * @memberof UserInput
     */
    id: string;
    /**
     * Avatar of the user.
     * @type {string}
     * @memberof UserInput
     */
    avatar?: string;
    /**
     * Firstname of the user.
     * @type {string}
     * @memberof UserInput
     */
    first_name?: string;
    /**
     * Lastname of the user.
     * @type {string}
     * @memberof UserInput
     */
    last_name?: string;
    /**
     * Email of the user.
     * @type {string}
     * @memberof UserInput
     */
    email?: string;
    /**
     * Values for CustomUserFields
     * @type {{ [key: string]: any; }}
     * @memberof UserInput
     */
    customFields?: { [key: string]: any; };
}

export function UserInputFromJSON(json: any): UserInput {
    return UserInputFromJSONTyped(json, false);
}

export function UserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
        'first_name': !exists(json, 'first_name') ? undefined : json['first_name'],
        'last_name': !exists(json, 'last_name') ? undefined : json['last_name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'customFields': !exists(json, 'customFields') ? undefined : json['customFields'],
    };
}

export function UserInputToJSON(value?: UserInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'avatar': value.avatar,
        'first_name': value.first_name,
        'last_name': value.last_name,
        'email': value.email,
        'customFields': value.customFields,
    };
}


