/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserConfig
 */
export interface UserConfig {
    /**
     * The URL of the Gravitee management UI
     * @type {string}
     * @memberof UserConfig
     */
    management_url?: string;
}

export function UserConfigFromJSON(json: any): UserConfig {
    return UserConfigFromJSONTyped(json, false);
}

export function UserConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'management_url': !exists(json, 'management_url') ? undefined : json['management_url'],
    };
}

export function UserConfigToJSON(value?: UserConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'management_url': value.management_url,
    };
}


