
http:
  instances: 1
  websocket:
    enabled: true
tcp:
  instances: 1
plugins:
    path: ${gravitee.home}/plugins

management:
  type: mock

ratelimit:
  type: mock

cache:
  type: mock

sync:
  enabled: false
  cron: '*/5 * * * * *'

tracing:
  enabled: false