databaseChangeLog:
  - changeSet:
      id: 4.9.0_00-add_hrid_applications_table
      author: GraviteeSource Team
      changes:
        # ################
        # Application Changes: Kubernetes Operator
        # ################
        - addColumn:
            tableName: ${gravitee_prefix}applications
            columns:
              - column:
                  name: hrid
                  type: nvarchar(256)
                  constraints:
                    nullable: true
