databaseChangeLog:
  - changeSet:
      id: 4.8.0_02_add_org_id_to_portal_and_generic_notification_configs
      author: GraviteeSource Team
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}portal_notification_configs
            columns:
              - column:
                  name: org_id
                  type: nvarchar(64)
                  constraints:
                    nullable: false
        - addColumn:
            tableName: ${gravitee_prefix}generic_notification_configs
            columns:
              - column:
                  name: org_id
                  type: nvarchar(64)
                  constraints:
                    nullable: false
