/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
export function AlertTriggerAnalyticsFromJSON(json) {
    return AlertTriggerAnalyticsFromJSONTyped(json, false);
}
export function AlertTriggerAnalyticsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'description': !exists(json, 'description') ? undefined : json['description'],
        'events_count': !exists(json, 'events_count') ? undefined : json['events_count'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'severity': !exists(json, 'severity') ? undefined : json['severity'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}
export function AlertTriggerAnalyticsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'description': value.description,
        'events_count': value.events_count,
        'id': value.id,
        'name': value.name,
        'severity': value.severity,
        'type': value.type,
    };
}
