/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
export function ApiMetricsFromJSON(json) {
    return ApiMetricsFromJSONTyped(json, false);
}
export function ApiMetricsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'buckets': !exists(json, 'buckets') ? undefined : json['buckets'],
        'global': !exists(json, 'global') ? undefined : json['global'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}
export function ApiMetricsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'buckets': value.buckets,
        'global': value.global,
        'metadata': value.metadata,
    };
}
