/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConditionFromJSONTyped, ConditionToJSON, } from './';
export function CompareConditionFromJSON(json) {
    return CompareConditionFromJSONTyped(json, false);
}
export function CompareConditionFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ConditionFromJSONTyped(json, ignoreDiscriminator),
        'property': json['property'],
        'operator': json['operator'],
        'multiplier': json['multiplier'],
        'property2': json['property2'],
    };
}
export function CompareConditionToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ConditionToJSON(value),
        'property': value.property,
        'operator': value.operator,
        'multiplier': value.multiplier,
        'property2': value.property2,
    };
}
/**
* @export
* @enum {string}
*/
export var CompareConditionOperatorEnum;
(function (CompareConditionOperatorEnum) {
    CompareConditionOperatorEnum["LT"] = "LT";
    CompareConditionOperatorEnum["LTE"] = "LTE";
    CompareConditionOperatorEnum["GTE"] = "GTE";
    CompareConditionOperatorEnum["GT"] = "GT";
})(CompareConditionOperatorEnum || (CompareConditionOperatorEnum = {}));
