/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
export function EndpointDiscoveryServiceFromJSON(json) {
    return EndpointDiscoveryServiceFromJSONTyped(json, false);
}
export function EndpointDiscoveryServiceFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'configuration': !exists(json, 'configuration') ? undefined : json['configuration'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
    };
}
export function EndpointDiscoveryServiceToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'configuration': value.configuration,
        'enabled': value.enabled,
        'provider': value.provider,
    };
}
