/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { HttpHeaderFromJSON, HttpHeaderToJSON, } from './';
export function HealthCheckRequestFromJSON(json) {
    return HealthCheckRequestFromJSONTyped(json, false);
}
export function HealthCheckRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'body': !exists(json, 'body') ? undefined : json['body'],
        'fromRoot': !exists(json, 'fromRoot') ? undefined : json['fromRoot'],
        'headers': !exists(json, 'headers') ? undefined : (json['headers'].map(HttpHeaderFromJSON)),
        'method': !exists(json, 'method') ? undefined : json['method'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}
export function HealthCheckRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'body': value.body,
        'fromRoot': value.fromRoot,
        'headers': value.headers === undefined ? undefined : (value.headers.map(HttpHeaderToJSON)),
        'method': value.method,
        'path': value.path,
    };
}
/**
* @export
* @enum {string}
*/
export var HealthCheckRequestMethodEnum;
(function (HealthCheckRequestMethodEnum) {
    HealthCheckRequestMethodEnum["CONNECT"] = "CONNECT";
    HealthCheckRequestMethodEnum["DELETE"] = "DELETE";
    HealthCheckRequestMethodEnum["GET"] = "GET";
    HealthCheckRequestMethodEnum["HEAD"] = "HEAD";
    HealthCheckRequestMethodEnum["OPTIONS"] = "OPTIONS";
    HealthCheckRequestMethodEnum["PATCH"] = "PATCH";
    HealthCheckRequestMethodEnum["POST"] = "POST";
    HealthCheckRequestMethodEnum["PUT"] = "PUT";
    HealthCheckRequestMethodEnum["TRACE"] = "TRACE";
    HealthCheckRequestMethodEnum["OTHER"] = "OTHER";
})(HealthCheckRequestMethodEnum || (HealthCheckRequestMethodEnum = {}));
