/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export var HealthcheckField;
(function (HealthcheckField) {
    HealthcheckField["ENDPOINT"] = "ENDPOINT";
    HealthcheckField["GATEWAY"] = "GATEWAY";
})(HealthcheckField || (HealthcheckField = {}));
export function HealthcheckFieldFromJSON(json) {
    return HealthcheckFieldFromJSONTyped(json, false);
}
export function HealthcheckFieldFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function HealthcheckFieldToJSON(value) {
    return value;
}
