/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
export function HttpProxyFromJSON(json) {
    return HttpProxyFromJSONTyped(json, false);
}
export function HttpProxyFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'host': !exists(json, 'host') ? undefined : json['host'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'port': !exists(json, 'port') ? undefined : json['port'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'useSystemProxy': !exists(json, 'useSystemProxy') ? undefined : json['useSystemProxy'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}
export function HttpProxyToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'enabled': value.enabled,
        'host': value.host,
        'password': value.password,
        'port': value.port,
        'type': value.type,
        'useSystemProxy': value.useSystemProxy,
        'username': value.username,
    };
}
/**
* @export
* @enum {string}
*/
export var HttpProxyTypeEnum;
(function (HttpProxyTypeEnum) {
    HttpProxyTypeEnum["HTTP"] = "HTTP";
    HttpProxyTypeEnum["SOCKS4"] = "SOCKS4";
    HttpProxyTypeEnum["SOCKS5"] = "SOCKS5";
})(HttpProxyTypeEnum || (HttpProxyTypeEnum = {}));
