/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export var LifecycleAction;
(function (LifecycleAction) {
    LifecycleAction["START"] = "START";
    LifecycleAction["STOP"] = "STOP";
})(LifecycleAction || (LifecycleAction = {}));
export function LifecycleActionFromJSON(json) {
    return LifecycleActionFromJSONTyped(json, false);
}
export function LifecycleActionFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function LifecycleActionToJSON(value) {
    return value;
}
