/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Type's name
 * @export
 * @enum {string}
 */
export var MembershipMemberType;
(function (MembershipMemberType) {
    MembershipMemberType["USER"] = "USER";
    MembershipMemberType["GROUP"] = "GROUP";
})(MembershipMemberType || (MembershipMemberType = {}));
export function MembershipMemberTypeFromJSON(json) {
    return MembershipMemberTypeFromJSONTyped(json, false);
}
export function MembershipMemberTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function MembershipMemberTypeToJSON(value) {
    return value;
}
