/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { RatingCommentFromJSON, RatingCommentToJSON, } from './';
export function PortalRatingFromJSON(json) {
    return PortalRatingFromJSONTyped(json, false);
}
export function PortalRatingFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'comment': !exists(json, 'comment') ? undefined : RatingCommentFromJSON(json['comment']),
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}
export function PortalRatingToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'comment': RatingCommentToJSON(value.comment),
        'enabled': value.enabled,
    };
}
