/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { ConditionFromJSONTyped, ConditionToJSON, SingleValueConditionFromJSON, SingleValueConditionToJSON, } from './';
export function RateConditionFromJSON(json) {
    return RateConditionFromJSONTyped(json, false);
}
export function RateConditionFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ConditionFromJSONTyped(json, ignoreDiscriminator),
        'operator': json['operator'],
        'threshold': json['threshold'],
        'comparison': SingleValueConditionFromJSON(json['comparison']),
        'duration': json['duration'],
        'timeUnit': !exists(json, 'timeUnit') ? undefined : json['timeUnit'],
        'sampleSize': !exists(json, 'sampleSize') ? undefined : json['sampleSize'],
    };
}
export function RateConditionToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ConditionToJSON(value),
        'operator': value.operator,
        'threshold': value.threshold,
        'comparison': SingleValueConditionToJSON(value.comparison),
        'duration': value.duration,
        'timeUnit': value.timeUnit,
        'sampleSize': value.sampleSize,
    };
}
/**
* @export
* @enum {string}
*/
export var RateConditionOperatorEnum;
(function (RateConditionOperatorEnum) {
    RateConditionOperatorEnum["LT"] = "LT";
    RateConditionOperatorEnum["LTE"] = "LTE";
    RateConditionOperatorEnum["GTE"] = "GTE";
    RateConditionOperatorEnum["GT"] = "GT";
})(RateConditionOperatorEnum || (RateConditionOperatorEnum = {}));
/**
* @export
* @enum {string}
*/
export var RateConditionTimeUnitEnum;
(function (RateConditionTimeUnitEnum) {
    RateConditionTimeUnitEnum["NANOSECONDS"] = "NANOSECONDS";
    RateConditionTimeUnitEnum["MICROSECONDS"] = "MICROSECONDS";
    RateConditionTimeUnitEnum["MILLISECONDS"] = "MILLISECONDS";
    RateConditionTimeUnitEnum["SECONDS"] = "SECONDS";
    RateConditionTimeUnitEnum["MINUTES"] = "MINUTES";
    RateConditionTimeUnitEnum["HOURS"] = "HOURS";
    RateConditionTimeUnitEnum["DAYS"] = "DAYS";
})(RateConditionTimeUnitEnum || (RateConditionTimeUnitEnum = {}));
