/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PlatformRequestItem,
    PlatformRequestItemFromJSON,
    PlatformRequestItemFromJSONTyped,
    PlatformRequestItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface SearchLogResponsePlatformRequestItem
 */
export interface SearchLogResponsePlatformRequestItem {
    /**
     * 
     * @type {Array<PlatformRequestItem>}
     * @memberof SearchLogResponsePlatformRequestItem
     */
    logs?: Array<PlatformRequestItem>;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof SearchLogResponsePlatformRequestItem
     */
    metadata?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {number}
     * @memberof SearchLogResponsePlatformRequestItem
     */
    total?: number;
}

export function SearchLogResponsePlatformRequestItemFromJSON(json: any): SearchLogResponsePlatformRequestItem {
    return SearchLogResponsePlatformRequestItemFromJSONTyped(json, false);
}

export function SearchLogResponsePlatformRequestItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchLogResponsePlatformRequestItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logs': !exists(json, 'logs') ? undefined : ((json['logs'] as Array<any>).map(PlatformRequestItemFromJSON)),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function SearchLogResponsePlatformRequestItemToJSON(value?: SearchLogResponsePlatformRequestItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'logs': value.logs === undefined ? undefined : ((value.logs as Array<any>).map(PlatformRequestItemToJSON)),
        'metadata': value.metadata,
        'total': value.total,
    };
}


