/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export var TaskType;
(function (TaskType) {
    TaskType["SUBSCRIPTIONAPPROVAL"] = "SUBSCRIPTION_APPROVAL";
    TaskType["INREVIEW"] = "IN_REVIEW";
    TaskType["REQUESTFORCHANGES"] = "REQUEST_FOR_CHANGES";
    TaskType["USERREGISTRATIONAPPROVAL"] = "USER_REGISTRATION_APPROVAL";
    TaskType["PROMOTIONAPPROVAL"] = "PROMOTION_APPROVAL";
})(TaskType || (TaskType = {}));
export function TaskTypeFromJSON(json) {
    return TaskTypeFromJSONTyped(json, false);
}
export function TaskTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function TaskTypeToJSON(value) {
    return value;
}
