/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ThemeDefinition,
    ThemeDefinitionFromJSON,
    ThemeDefinitionFromJSONTyped,
    ThemeDefinitionToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateThemeEntity
 */
export interface UpdateThemeEntity {
    /**
     * 
     * @type {string}
     * @memberof UpdateThemeEntity
     */
    backgroundImage?: string;
    /**
     * 
     * @type {ThemeDefinition}
     * @memberof UpdateThemeEntity
     */
    definition: ThemeDefinition;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateThemeEntity
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateThemeEntity
     */
    favicon?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateThemeEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateThemeEntity
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateThemeEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateThemeEntity
     */
    optionalLogo?: string;
}

export function UpdateThemeEntityFromJSON(json: any): UpdateThemeEntity {
    return UpdateThemeEntityFromJSONTyped(json, false);
}

export function UpdateThemeEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateThemeEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'backgroundImage': !exists(json, 'backgroundImage') ? undefined : json['backgroundImage'],
        'definition': ThemeDefinitionFromJSON(json['definition']),
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'favicon': !exists(json, 'favicon') ? undefined : json['favicon'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
        'name': json['name'],
        'optionalLogo': !exists(json, 'optionalLogo') ? undefined : json['optionalLogo'],
    };
}

export function UpdateThemeEntityToJSON(value?: UpdateThemeEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'backgroundImage': value.backgroundImage,
        'definition': ThemeDefinitionToJSON(value.definition),
        'enabled': value.enabled,
        'favicon': value.favicon,
        'id': value.id,
        'logo': value.logo,
        'name': value.name,
        'optionalLogo': value.optionalLogo,
    };
}


