title: |
  [${application.name}] Subscription Transferred
message: |
  The subscription to the plan "${plan.name}"
  of the <#if api??>api "${api.name}"<#elseif apiProduct??>API Product "${apiProduct.name}"<#else>api/product</#if> was transferred.