/*
 * Copyright © 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.gravitee.apim.infra.zee;

import com.jsonschema.llm.engine.ChatCompletionsFormatter;
import com.jsonschema.llm.engine.LlmRequest;
import com.jsonschema.llm.engine.LlmRoundtripEngine;
import com.jsonschema.llm.engine.LlmTransport;
import com.jsonschema.llm.engine.LlmTransportException;
import com.jsonschema.llm.engine.ProviderConfig;
import com.jsonschema.llm.engine.RoundtripResult;
import io.gravitee.apim.core.zee.domain_service.LlmEngineService;
import io.gravitee.apim.definition.llm.v4.JsonPatchOp;
import io.gravitee.apim.definition.llm.v4.SchemaGenerator;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Infrastructure implementation of {@link LlmEngineService} using the
 * {@code json-schema-llm} roundtrip engine with Azure OpenAI.
 *
 * <p>
 * Delegates all component dispatch to
 * {@link SchemaGenerator#generate(SchemaGenerator.Component, String, LlmRoundtripEngine)}
 * — the unified facade generated by the upstream SDK. The only special case is
 * the {@code Api} component, which receives an RFC 6902 JSON Patch to inject a
 * {@code description} property at generation time.
 *
 * @author Derek Burger
 */
@Component
public class LlmEngineServiceImpl implements LlmEngineService {

    private static final Logger LOG = LoggerFactory.getLogger(LlmEngineServiceImpl.class);
    private static final Duration HTTP_TIMEOUT = Duration.ofSeconds(300);

    /**
     * RFC 6902 JSON Patch that adds a {@code description} property to the Api
     * schema and replaces the opaque {@code configuration} in embedded Endpoints
     * with a typed object requiring {@code target}.
     */
    private static final List<JsonPatchOp> API_PATCHES = List.of(
            new JsonPatchOp.Add(
                    "/properties/description",
                    Map.of("type", "string", "description", "Human-readable description of the API.")),
            new JsonPatchOp.Replace(
                    "/$defs/Endpoint/properties/configuration",
                    Map.of("type", "object",
                            "description", "Endpoint-specific configuration.",
                            "properties", Map.of("target",
                                    Map.of("type", "string",
                                            "description",
                                            "The target backend HTTP URL (e.g. https://api.example.com).")),
                            "required", List.of("target"))));

    /**
     * RFC 6902 JSON Patch to replace the opaque {@code configuration} in
     * EndpointGroup's embedded Endpoint with a typed object requiring
     * {@code target}.
     */
    private static final List<JsonPatchOp> ENDPOINT_GROUP_PATCHES = List.of(
            new JsonPatchOp.Replace(
                    "/$defs/Endpoint/properties/configuration",
                    Map.of("type", "object",
                            "description", "Endpoint-specific configuration.",
                            "properties", Map.of("target",
                                    Map.of("type", "string",
                                            "description",
                                            "The target backend HTTP URL (e.g. https://api.example.com).")),
                            "required", List.of("target"))));

    /**
     * RFC 6902 JSON Patch to replace the opaque {@code configuration} in
     * the standalone Endpoint schema with a typed object requiring {@code target}.
     */
    private static final List<JsonPatchOp> ENDPOINT_PATCHES = List.of(
            new JsonPatchOp.Replace(
                    "/properties/configuration",
                    Map.of("type", "object",
                            "description", "Endpoint-specific configuration.",
                            "properties", Map.of("target",
                                    Map.of("type", "string",
                                            "description",
                                            "The target backend HTTP URL (e.g. https://api.example.com).")),
                            "required", List.of("target"))));

    private final boolean disabled;
    private final LlmRoundtripEngine engine;

    @Autowired
    public LlmEngineServiceImpl(ZeeConfiguration config) {
        this(config, HttpClient.newHttpClient());
    }

    /**
     * Visible-for-testing constructor that accepts a custom {@link HttpClient}.
     */
    LlmEngineServiceImpl(ZeeConfiguration config, HttpClient httpClient) {
        if (!config.isEnabled()) {
            LOG.info("Zee Mode is disabled (ai.zee.enabled=false) — LLM engine will not be initialized");
            this.disabled = true;
            this.engine = null;
            return;
        }
        this.disabled = false;

        Objects.requireNonNull(config.getAzureUrl(), "ai.zee.azure.url must be configured when ai.zee.enabled=true");
        Objects.requireNonNull(config.getAzureApiKey(),
                "ai.zee.azure.apiKey must be configured when ai.zee.enabled=true");

        var providerConfig = new ProviderConfig(config.getAzureUrl(), config.getAzureModel(),
                Map.of("api-key", config.getAzureApiKey()));

        LlmTransport transport = request -> executeHttp(httpClient, request);

        this.engine = LlmRoundtripEngine.create(new ChatCompletionsFormatter(), providerConfig, transport);

        LOG.info("Zee LLM engine initialized — endpoint: {}", config.getAzureUrl());
    }

    /**
     * Visible-for-testing constructor that accepts a pre-built engine.
     */
    LlmEngineServiceImpl(LlmRoundtripEngine engine) {
        this.disabled = false;
        this.engine = engine;
    }

    @Override
    public LlmGenerationResult generate(String prompt, String componentName) {
        if (disabled) {
            throw new IllegalStateException(
                    "Zee Mode is disabled. Set ai.zee.enabled=true with valid Azure credentials.");
        }

        SchemaGenerator.Component component;
        try {
            component = SchemaGenerator.Component.from(componentName);
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException(
                    "Unsupported component: " + componentName + ". Available: " +
                            java.util.Arrays.toString(SchemaGenerator.Component.values()));
        }

        try {
            RoundtripResult result;
            if (component == SchemaGenerator.Component.API) {
                result = SchemaGenerator.generate(component, prompt, engine, API_PATCHES);
            } else if (component == SchemaGenerator.Component.ENDPOINT_GROUP) {
                result = SchemaGenerator.generate(component, prompt, engine, ENDPOINT_GROUP_PATCHES);
            } else if (component == SchemaGenerator.Component.ENDPOINT) {
                result = SchemaGenerator.generate(component, prompt, engine, ENDPOINT_PATCHES);
            } else {
                result = SchemaGenerator.generate(component, prompt, engine);
            }
            return toGenerationResult(result);
        } catch (IOException e) {
            throw new RuntimeException("Failed to load schema resources for component: " + componentName, e);
        } catch (LlmTransportException e) {
            throw new RuntimeException("LLM transport failed for component: " + componentName, e);
        }
    }

    private static LlmGenerationResult toGenerationResult(RoundtripResult result) {
        return new LlmGenerationResult(result.data(), result.isValid(), -1, result.warnings(),
                result.validationErrors());
    }

    private static String executeHttp(HttpClient httpClient, LlmRequest request) throws LlmTransportException {
        try {
            var builder = HttpRequest.newBuilder()
                    .uri(URI.create(request.url()))
                    .timeout(HTTP_TIMEOUT)
                    .POST(HttpRequest.BodyPublishers.ofString(request.body()));

            request.headers().forEach(builder::header);

            var response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() >= 400) {
                throw new LlmTransportException(
                        "Azure OpenAI returned HTTP " + response.statusCode() + ": " + truncate(response.body(), 500),
                        response.statusCode());
            }

            LOG.info("LLM Response body: {}", truncate(response.body(), 2000));
            return response.body();
        } catch (LlmTransportException e) {
            throw e;
        } catch (Exception e) {
            throw new LlmTransportException("HTTP transport failed: " + e.getMessage(), 0, e);
        }
    }

    private static String truncate(String s, int maxLen) {
        return s != null && s.length() > maxLen ? s.substring(0, maxLen) + "..." : s;
    }
}
