= Gravitee Redis Repository

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-repository-redis/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-repository-redis"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Overview

Redis repository based on Redis implementation

== Requirement

The minimum requirement is :
 * Maven3
 * Jdk8

For user gravitee snapshot, You need the declare the following repository in you maven settings :

https://oss.sonatype.org/content/repositories/snapshots

== Building

```
$ cd gravitee-apim-repository/gravitee-apim-repository-redis
$ mvn clean package
```

== Installing

Unzip the gravitee-repository-redis-3.1.0-SNAPSHOT.zip in the gravitee home directory.

== Configuration

  repository.redis options (standalone) :

  | Parameter                                        |   default  |
  | ------------------------------------------------ | ---------: |
  | host                                             | localhost  |
  | port                                             |      6379  |
  | password                                         |            |
  | timeout                                          |   1000 ms  |

  repository.redis options (using sentinel) :

  | Parameter                                        |   default  |
  | ------------------------------------------------ | ---------: |
  | sentinel.nodes                                   |            |
  | sentinel.password                                |            |
  | sentinel.master (mandatory when using Sentinel)  |            |
  | password                                         |            |
  | timeout                                          |   1000 ms  |

Examples :

_Standalone redis_ :

[source,yaml]
----
redis:
  host: 'redis.mycompany'
  port: 6379
  password: 'mysecretpassword'
  timeout: 2000
----

_Redis replicaset behind Sentinels_ :

[source,yaml]
----
redis:
  sentinel:
    master: 'mymaster'
    nodes:
      - host: 'sentinel-1.mycompany'
        port: 26379
      - host: 'sentinel-2.mycompany'
        port: 26379
      - host: 'sentinel-3.mycompany'
        port: 26379
    password: 'sentinel-password'
  password: 'redis-password'
  timeout: 2000
----