== Gravitee.io API Management - Portal

This project was generated with https://github.com/angular/angular-cli[Angular CLI] version 9.1.1.

== Install

- Install https://github.com/nvm-sh/nvm[nvm]
- Install the Angular CLI
```
npm install -g @angular/cli
```
- Use with `nvm use` or install with `nvm install` the node version declared in `.nvmrc`
- Then install node modules with:
```
npm install
```

== Development server

Run `npm run serve` for a dev server. Navigate to `http://localhost:4100/`.
The app will automatically reload if you change any of the source files.

== Code scaffolding

Run `ng generate component component-name` to generate a new component.
You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

== Build

Run `npm run build` to build the project.
The build artifacts will be stored in the `dist/` directory.
Use the `npm run build:prod` for a production build.
Use the `npm run serve:prod` flag for a production build.

== Running unit tests

Run `npm run test` to execute the unit tests via https://jestjs.io/[Jest].

== Running end-to-end tests

Run `npm run e2e` to execute the end-to-end tests via http://www.protractortest.org/[Protractor].

== Further help

To get more help on the Angular CLI use `ng help` or go check out the https://github.com/angular/angular-cli/blob/master/README.md[Angular CLI README].

== About dependencies

This project use project https://github.com/gravitee-io/gravitee-ui-components[Gravitee UI Components].
If you want to develop in parallel, you can clone repository and link to project.

```shell script
git clone git@github.com:gravitee-io/gravitee-ui-components.git
pushd gravitee-ui-components
npm run generate:dist
npm link
popd

pushd gravitee-api-portal-webui
npm link @gravitee/ui-components
popd
```

This project use project https://github.com/OpenAPITools/openapi-generator[openapi-generator] to generate a client sdk with openapi file.
If you want to generate the client, run `npm run update:sdk`

== Review

If you want review a pull request with changes on https://github.com/gravitee-io/gravitee-ui-components[Gravitee UI Components] dependency, you can use link:scripts/install.sh[]
for automatic installation of branch with same name.
Don't forget to reset your package.json and package-lock.json after reviewing.


== i18n

This project use the internationalization (i18n) library for Angular http://www.ngx-translate.com

If you want extract translatable strings and merges with existing if the JSON file already exists, run:

```
npm run generate:i18n
```

== Start in production mode

If you want to test the deliverable in production mode :

```
npm run build:prod
npm run serve:prod
```

== Tips

If you want to test with apim master backend:
```
npm run serve:apim-master
```
