databaseChangeLog:
  - changeSet:
      id: 3.17.0
      author: GraviteeSource Team
      validCheckSum: ANY
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}applications
            columns:
              - column:
                  name: api_key_mode
                  type: nvarchar(16)
                  constraints:
                    nullable: true
        - createTable:
            tableName: ${gravitee_prefix}key_subscriptions
            columns:
              - column: {name: key_id, type: nvarchar(64), constraints: { nullable: false, primaryKey: true, primaryKeyName: "pk_${gravitee_prefix}key_subscriptions" } }
              - column: {name: subscription_id, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
        - dropNotNullConstraint:
            columnDataType: nvarchar(64)
            columnName: api
            tableName: ${gravitee_prefix}keys
        - dropNotNullConstraint:
            columnDataType: nvarchar(64)
            columnName: plan
            tableName: ${gravitee_prefix}keys
        - dropNotNullConstraint:
            columnDataType: nvarchar(64)
            columnName: subscription
            tableName: ${gravitee_prefix}keys
