/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlertType } from './alertType';
import { AlertWebhook } from './alertWebhook';
import { AlertTimeUnit } from './alertTimeUnit';


export interface AlertInput { 
    /**
     * Concerned application ID
     */
    application?: string;
    type?: AlertType;
    /**
     * Filter on API id (empty for all apis)
     */
    api?: string;
    /**
     * Alert description
     */
    description?: string;
    /**
     * Http status code to trigger the alert
     */
    status_code?: string;
    /**
     * Percent to trigger the alert on status code
     */
    status_percent?: number;
    /**
     * true, if alert is enabled
     */
    enabled?: boolean;
    /**
     * Response time to trigger the alert
     */
    response_time?: number;
    /**
     * Compute alert on selected duration
     */
    duration?: number;
    time_unit?: AlertTimeUnit;
    webhook?: AlertWebhook;
}

