/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationRole } from './applicationRole';


export interface ConfigurationApplicationRolesResponse { 
    /**
     * List of application roles
     */
    data?: Array<ApplicationRole>;
}

