/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageMedia { 
    /**
     * the name of the media.
     */
    name: string;
    /**
     * link to download the media.
     */
    link: string;
    /**
     * type of the media.
     */
    type: string;
}

