/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Consumer configuration associated to the subscription in case it is attached to a push plan.
 */
export interface SubscriptionConsumerConfiguration { 
    /**
     * The id of the targeted entrypoint
     */
    entrypointId: string;
    /**
     * The channel to consume
     */
    channel?: string;
    /**
     * The configuration to use at subscription time to push to the target service.
     */
    entrypointConfiguration?: object;
}

