= MQTT 5.x Endpoint

== Description

This is an _OSS_ edition for MQTT 5.x endpoint which allow subscribing or publishing messages to a MQTT 5.x broker such as HiveMQ or Mosquitto.

=== Quality Of Service

|===
|QoS           |  Delivery        | Description
|None          | Unwarranted      | Use default MQTT QoS
|Balanced      | 0, 1 or n        | Use default MQTT QoS
|===

== Compatibility matrix

|===
|Plugin version | APIM version

|1.x and upper                  | 3.21.x to latest
|===

== Endpoint identifier

In order to use this _OSS_ version, you have to declare the following identifier `mqtt5` while configuring your API endpoints.

== Endpoint configuration

=== General configuration

==== Endpoint level configuration

|===
|Attributes | Default | Mandatory | Description

|serverHost | N/A     | Yes | Define the host of the MQTT broker.
|serverPort | N/A     | Yes | Define the port of the MQTT broker.
|===

==== Shared configuration

Shared configuration can be done directly from the endpoint group `sharedConfiguration` field.

If `inheritConfiguration` is false, then shared configuration can be overridden directly from endpoint `overriddenSharedConfiguration` field.

|===
|Attributes | Default | Mandatory | Description

|reconnectAttempts | N/A     | No | The number of attempt to reconnect to the broker.
|===

===== Consumer configuration

|===
|Attributes | Default | Mandatory | Description

|enabled | false     | No | Allow enabling or disabling the consumer capability.
|topic | N/A     | Yes | Refers to an UTF-8 string that the broker uses to filter messages for each connected client.
|===

===== Producer configuration
|===
|Attributes | Default | Mandatory | Description

|enabled | false     | No | Allow enabling or disabling the producer capability.
|topic | N/A     | Yes | Refers to an UTF-8 string that the broker uses to filter messages for each connected client.
|retained | false     | No | Define if the retain flag must be set to every publish messages.
|responseTopic |  N/A     | No | The response topic represents the topics on which the responses from the receivers of the message are expected.
|===

=== Examples

Bellow you will find a full mqtt endpoint configuration example:

```json
{
    "name": "default",
    "type": "mqtt5",
    "weight": 1,
    "inheritConfiguration": false,
    "configuration": {
        "identifier": "gio-apim-identifier",
        "serverHost": "localhost",
        "serverPort": "1883"
    },
    "sharedConfigurationOverride": {
        "consumer" : {
            "enabled": true,
            "topic": "python/mqtt"
        },
        "producer": {
            "enabled": true,
            "topic": "python/mqtt",
            "retained": false,
            "responseTopic": "python/mqtt/response"
        }
    }
}
```

