{{- if .Values.gateway.enabled -}}
{{- $gatewayName := .Values.gateway.name | trunc 63 | trimSuffix "-"}}
{{- $appPrototcolSupported := (include "common.service.supportsAppProtocol" .)}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- if and .Values.common .Values.common.labels }}
    {{- range $key, $value := .Values.common.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  annotations:
    {{- if and .Values.common .Values.common.annotations }}
    {{- range $key, $value := .Values.common.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.gateway.service.annotations }}
    {{- range $key, $value := .Values.gateway.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.gateway.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.gateway.service.loadBalancerIP }}"
  {{- end }}
  {{- if eq .Values.gateway.service.type "LoadBalancer" }}
  {{- if .Values.gateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: 
  {{ toYaml .Values.gateway.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  type: "{{ .Values.gateway.service.type }}"
  {{- if eq .Values.gateway.service.type "NodePort" "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.gateway.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    {{- if .Values.gateway.servers }}
    {{- range $i, $server := .Values.gateway.servers }}
    - port: {{ $server.service.externalPort }}
      targetPort: {{ $server.port }}
      {{- if eq $server.service.type "NodePort" }}
      {{- if $server.service.nodePort }}
      nodePort: {{ $server.service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      {{- if $appPrototcolSupported }}
      {{ if $server.service.appProtocol }}
      appProtocol: {{ $server.service.appProtocol }}
      {{ end }}
      {{- end }}
      name: {{ printf "%s-%d" ($gatewayName | trunc 60 | trimSuffix "-") $i}}
    {{- end }}
    {{- else }}
    - port: {{ .Values.gateway.service.externalPort }}
      targetPort: {{ .Values.gateway.service.internalPort }}
      {{- if eq .Values.gateway.service.type "NodePort" }}
      {{- if .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      {{- if $appPrototcolSupported }}
      {{ if .Values.gateway.service.appProtocol }}
      appProtocol: {{ .Values.gateway.service.appProtocol }}
      {{ else if .Values.gateway.ssl.enabled }}
      appProtocol: https
      {{ else }}
      appProtocol: http
      {{ end }}
      {{- end }}
      name: {{ $gatewayName }}
    {{- end }}
    {{- if hasKey .Values.gateway "kafka" }}
    {{- if and .Values.gateway.kafka.enabled .Values.gateway.services.kafka.enabled }}
    - port: {{ .Values.gateway.services.kafka.service.externalPort }}
      targetPort: {{ .Values.gateway.services.kafka.service.internalPort }}
      protocol: TCP
      name: {{ printf "%s-%s" (.Values.gateway.name | trunc 53 | trimSuffix "-") "kafka" }}
    {{- end }}
    {{- end }}
    {{- if .Values.gateway.services.bridge.enabled }}
    - port: {{ .Values.gateway.services.bridge.service.externalPort }}
      targetPort: {{ .Values.gateway.services.bridge.service.internalPort }}
      protocol: TCP
      {{- if (include "common.service.supportsAppProtocol" .) }}
      {{ if .Values.gateway.services.bridge.service.appProtocol }}
      appProtocol: {{ .Values.gateway.services.bridge.service.appProtocol }}
      {{ else if .Values.gateway.services.bridge.ssl.enabled }}
      appProtocol: https
      {{ else }}
      appProtocol: http
      {{ end }}
      {{- end }}
      name: {{ printf "%s-%s" (.Values.gateway.name | trunc 56 | trimSuffix "-") "bridge" }}
    {{- end }}
    {{- if .Values.gateway.services.core.service.enabled }}
    - port: {{ .Values.gateway.services.core.service.externalPort }}
      targetPort: {{ .Values.gateway.services.core.http.port }}
      protocol: TCP
      {{- if (include "common.service.supportsAppProtocol" .) }}
      {{ if .Values.gateway.services.core.service.appProtocol }}
      appProtocol: {{ .Values.gateway.services.core.service.appProtocol }}
      {{ else }}
      appProtocol: http
      {{ end }}
      {{- end }}
      name: {{ printf "%s-%s" (.Values.gateway.name | trunc 53 | trimSuffix "-") "technical" }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
{{- end -}}
