databaseChangeLog:
  - changeSet:
      id: 4.9.17_01_change_generic_notification_config_datatype
      author: GraviteeSource Team
      changes:
        - modifyDataType:
            tableName: ${gravitee_prefix}generic_notification_configs
            columnName: config
            newDataType: nvarchar(2048)
