/*
 * Copyright © 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.gravitee.rest.api.service.catalog.quality;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import org.springframework.stereotype.Service;

@Service
public class TitleDescriptionScoringService {

    private static final int TITLE_MIN_SWEET_SPOT = 10;
    private static final int TITLE_MAX_SWEET_SPOT = 80;
    private static final int DESC_MIN_LENGTH = 30;
    private static final int DESC_SWEET_SPOT_MIN = 100;
    private static final int DESC_SWEET_SPOT_MAX = 500;
    private static final int DESC_EXCESSIVE_LENGTH = 1000;

    private static final Pattern KEBAB_SNAKE_PATTERN = Pattern.compile("^[a-z0-9]+([_-][a-z0-9]+)+$");

    private static final Set<String> GENERIC_TITLES = Set.of(
        "my api",
        "test",
        "test api",
        "untitled",
        "new api",
        "api",
        "sample",
        "sample api",
        "default",
        "default api",
        "example",
        "example api",
        "demo",
        "demo api",
        "api-1",
        "api_1",
        "hello world"
    );

    private static final Pattern GENERIC_TITLE_PATTERN = Pattern.compile(
        "^(my[- _]?api|test[- _]?\\d*|api[- _]?\\d+|untitled[- _]?\\d*|new[- _]?api[- _]?\\d*)$",
        Pattern.CASE_INSENSITIVE
    );

    private static final Set<String> STOP_WORDS = Set.of(
        "a",
        "an",
        "the",
        "is",
        "it",
        "of",
        "for",
        "to",
        "in",
        "on",
        "and",
        "or",
        "with",
        "this",
        "that",
        "api",
        "service",
        "v1",
        "v2",
        "v3",
        "v4"
    );

    private static final Set<String> DOMAIN_VERBS = Set.of(
        "create",
        "manage",
        "retrieve",
        "authenticate",
        "process",
        "sync",
        "calculate",
        "update",
        "charge",
        "validate",
        "notify",
        "transform",
        "search",
        "delete",
        "upload",
        "download",
        "monitor",
        "schedule",
        "authorize",
        "encrypt",
        "generate",
        "analyze",
        "configure",
        "deploy",
        "subscribe",
        "publish",
        "route",
        "aggregate",
        "stream",
        "convert"
    );

    private static final Pattern BOILERPLATE_PATTERN = Pattern.compile(
        "(auto[- ]?generated|swagger definition for|rest api for|server stub|no description|" +
            "this is (a|an|the) (auto|server|default)|generated by|openapi generator|" +
            "todo:? (add|write|fill)|placeholder)",
        Pattern.CASE_INSENSITIVE
    );

    public CatalogQualityScoringResult scoreTitle(String title) {
        int score = 0;
        var issues = new ArrayList<String>();

        if (title == null || title.isBlank()) {
            issues.add("Title is missing");
            return new CatalogQualityScoringResult(0, issues);
        }

        score += 5;

        var trimmed = title.trim();
        int len = trimmed.length();

        if (len >= TITLE_MIN_SWEET_SPOT && len <= TITLE_MAX_SWEET_SPOT) {
            score += 10;
        } else if (len < TITLE_MIN_SWEET_SPOT) {
            score += Math.max(0, (len * 10) / TITLE_MIN_SWEET_SPOT);
            issues.add(
                "Title is too short (%d chars) — aim for %d-%d characters".formatted(len, TITLE_MIN_SWEET_SPOT, TITLE_MAX_SWEET_SPOT)
            );
        } else {
            score += 5;
            issues.add("Title is very long (%d chars) — consider shortening to under %d characters".formatted(len, TITLE_MAX_SWEET_SPOT));
        }

        if (isHumanReadable(trimmed)) {
            score += 10;
        } else {
            issues.add(
                "Title uses kebab-case or snake_case — use natural language with spaces for better discovery (e.g. \"Customer Account Service\" instead of \"customer-account-service\")"
            );
        }

        if (!isGenericTitle(trimmed)) {
            score += 10;
        } else {
            issues.add("Title is too generic — use a specific, descriptive name");
        }

        int meaningfulWords = countMeaningfulWords(trimmed);
        if (meaningfulWords >= 2) {
            score += 15;
        } else {
            score += (meaningfulWords * 15) / 2;
            issues.add("Title should contain at least 2 meaningful words for effective semantic search");
        }

        return new CatalogQualityScoringResult(Math.min(score, 50), issues);
    }

    public CatalogQualityScoringResult scoreDescription(String description, String title) {
        int score = 0;
        var issues = new ArrayList<String>();

        if (description == null || description.isBlank()) {
            issues.add("Description is missing — this severely impacts catalog discoverability");
            return new CatalogQualityScoringResult(0, issues);
        }

        score += 5;

        var trimmed = description.trim();
        int len = trimmed.length();

        if (len >= DESC_MIN_LENGTH) {
            score += 10;
        } else {
            score += Math.max(0, (len * 10) / DESC_MIN_LENGTH);
            issues.add("Description is too short (%d chars) — aim for at least %d characters".formatted(len, DESC_MIN_LENGTH));
        }

        if (title != null && !title.isBlank() && isDuplicateOfTitle(trimmed, title.trim())) {
            issues.add("Description is too similar to the title — add information about what the API does, its use cases, or its domain");
        } else {
            score += 15;
        }

        if (len >= DESC_SWEET_SPOT_MIN && len <= DESC_SWEET_SPOT_MAX) {
            score += 10;
        } else if (len < DESC_SWEET_SPOT_MIN && len >= DESC_MIN_LENGTH) {
            score += 5;
            issues.add(
                "Description could be more detailed (%d chars) — the sweet spot for semantic search is %d-%d characters".formatted(
                    len,
                    DESC_SWEET_SPOT_MIN,
                    DESC_SWEET_SPOT_MAX
                )
            );
        } else if (len > DESC_SWEET_SPOT_MAX && len <= DESC_EXCESSIVE_LENGTH) {
            score += 7;
        } else if (len > DESC_EXCESSIVE_LENGTH) {
            score += 3;
            issues.add(
                "Description is excessively long (%d chars) — the core purpose may be buried; aim for %d-%d characters of focused content".formatted(
                    len,
                    DESC_SWEET_SPOT_MIN,
                    DESC_SWEET_SPOT_MAX
                )
            );
        }

        if (containsDomainVerbs(trimmed)) {
            score += 10;
        } else {
            issues.add(
                "Description lacks action verbs — include what the API does (e.g. \"manages\", \"retrieves\", \"authenticates\", \"processes\")"
            );
        }

        if (BOILERPLATE_PATTERN.matcher(trimmed).find()) {
            score -= 10;
            issues.add(
                "Description contains auto-generated boilerplate text — replace with a human-written description of the API's purpose"
            );
        }

        return new CatalogQualityScoringResult(Math.max(0, Math.min(score, 50)), issues);
    }

    private boolean isHumanReadable(String title) {
        if (title.contains(" ")) {
            return true;
        }
        return !KEBAB_SNAKE_PATTERN.matcher(title).matches();
    }

    private boolean isGenericTitle(String title) {
        var lower = title.toLowerCase().trim();
        if (GENERIC_TITLES.contains(lower)) {
            return true;
        }
        return GENERIC_TITLE_PATTERN.matcher(lower).matches();
    }

    private int countMeaningfulWords(String text) {
        var words = text.split("[\\s\\-_]+");
        int count = 0;
        for (var word : words) {
            var lower = word.toLowerCase().replaceAll("[^a-z]", "");
            if (!lower.isEmpty() && !STOP_WORDS.contains(lower)) {
                count++;
            }
        }
        return count;
    }

    private boolean isDuplicateOfTitle(String description, String title) {
        var descNorm = description.toLowerCase().replaceAll("[^a-z0-9 ]", "").trim();
        var titleNorm = title.toLowerCase().replaceAll("[^a-z0-9 ]", "").trim();

        if (descNorm.equals(titleNorm)) {
            return true;
        }
        if (descNorm.startsWith(titleNorm) && descNorm.length() < titleNorm.length() * 1.5) {
            return true;
        }
        return false;
    }

    private boolean containsDomainVerbs(String text) {
        var lower = text.toLowerCase();
        for (var verb : DOMAIN_VERBS) {
            if (lower.contains(verb)) {
                return true;
            }
        }
        return false;
    }
}
