{{- if and (.Values.api.enabled) (not .Values.apim.dbLess) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.api.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- if and .Values.common .Values.common.labels }}
    {{- range $key, $value := .Values.common.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.api.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if and .Values.common .Values.common.annotations }}
    {{- range $key, $value := .Values.common.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  type: "{{ .Values.api.service.type }}"
  {{- if eq .Values.api.service.type "NodePort" "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.api.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.api.service.externalPort }}
      targetPort: {{ .Values.api.service.internalPort }}
      {{- if eq .Values.api.service.type "NodePort" }}
      {{- if .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      {{- if (include "common.service.supportsAppProtocol" .) }}
      {{ if .Values.api.service.appProtocol }}
      appProtocol: {{ .Values.api.service.appProtocol }}
      {{ else }}
      {{ if .Values.api.ssl.enabled }}
      appProtocol: https
      {{ else }}
      appProtocol: http
      {{ end }}
      {{ end }}
      {{- end }}
      name: {{ .Values.api.name | trunc 63 | trimSuffix "-" }}
    {{- if .Values.api.http.services.core.service.enabled }}
    - port: {{ .Values.api.http.services.core.service.externalPort }}
      targetPort: {{ .Values.api.http.services.core.http.port }}
      protocol: TCP
      {{- if (include "common.service.supportsAppProtocol" .) }}
      {{ if .Values.api.http.services.core.service.appProtocol }}
      appProtocol: {{ .Values.api.http.services.core.service.appProtocol }}
      {{ else }}
      appProtocol: http
      {{ end }}
      {{- end }}
      name: {{ printf "%s-%s" (.Values.api.name | trunc 53 | trimSuffix "-") "technical" }}
    {{- end }}
    {{- if .Values.api.services.bridge.enabled }}
    - port: {{ .Values.api.services.bridge.service.externalPort }}
      targetPort: {{ .Values.api.services.bridge.service.internalPort }}
      protocol: TCP
      {{- if (include "common.service.supportsAppProtocol" .) }}
      {{ if .Values.api.services.bridge.service.appProtocol }}
      appProtocol: {{ .Values.api.services.bridge.service.appProtocol }}
      {{ else if .Values.api.services.bridge.ssl.enabled }}
      appProtocol: https
      {{ else }}
      appProtocol: http
      {{ end }}
      {{- end }}
      name: {{ printf "%s-%s" (.Values.api.name | trunc 56 | trimSuffix "-") "bridge" }}
    {{- end }}
    {{- if .Values.api.federation.enabled }}
    - port: {{ .Values.api.federation.service.externalPort }}
      targetPort: {{ .Values.api.federation.port }}
      protocol: TCP
      name: {{ printf "%s-%s" (.Values.api.name | trunc 56 | trimSuffix "-") "integration-controller" }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
{{- end -}}