/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApisOrderParam
 */
export interface ApisOrderParam {
    /**
     * 
     * @type {string}
     * @memberof ApisOrderParam
     */
    value?: ApisOrderParamValueEnum;
    /**
     * 
     * @type {string}
     * @memberof ApisOrderParam
     */
    originalParam?: string;
}

export function ApisOrderParamFromJSON(json: any): ApisOrderParam {
    return ApisOrderParamFromJSONTyped(json, false);
}

export function ApisOrderParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApisOrderParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'originalParam': !exists(json, 'originalParam') ? undefined : json['originalParam'],
    };
}

export function ApisOrderParamToJSON(value?: ApisOrderParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'originalParam': value.originalParam,
    };
}

/**
* @export
* @enum {string}
*/
export enum ApisOrderParamValueEnum {
    Name = 'name',
    Name = '-name',
    Paths = 'paths',
    Paths = '-paths'
}


