/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsoleReCaptcha
 */
export interface ConsoleReCaptcha {
    /**
     * 
     * @type {boolean}
     * @memberof ConsoleReCaptcha
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConsoleReCaptcha
     */
    siteKey?: string;
}

export function ConsoleReCaptchaFromJSON(json: any): ConsoleReCaptcha {
    return ConsoleReCaptchaFromJSONTyped(json, false);
}

export function ConsoleReCaptchaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleReCaptcha {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'siteKey': !exists(json, 'siteKey') ? undefined : json['siteKey'],
    };
}

export function ConsoleReCaptchaToJSON(value?: ConsoleReCaptcha | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'siteKey': value.siteKey,
    };
}


