/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Dampening
 */
export interface Dampening {
    /**
     * 
     * @type {string}
     * @memberof Dampening
     */
    mode: DampeningModeEnum;
    /**
     * 
     * @type {number}
     * @memberof Dampening
     */
    trueEvaluations?: number;
    /**
     * 
     * @type {number}
     * @memberof Dampening
     */
    totalEvaluations?: number;
    /**
     * 
     * @type {number}
     * @memberof Dampening
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof Dampening
     */
    timeUnit?: DampeningTimeUnitEnum;
}

export function DampeningFromJSON(json: any): Dampening {
    return DampeningFromJSONTyped(json, false);
}

export function DampeningFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dampening {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'trueEvaluations': !exists(json, 'trueEvaluations') ? undefined : json['trueEvaluations'],
        'totalEvaluations': !exists(json, 'totalEvaluations') ? undefined : json['totalEvaluations'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'timeUnit': !exists(json, 'timeUnit') ? undefined : json['timeUnit'],
    };
}

export function DampeningToJSON(value?: Dampening | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mode': value.mode,
        'trueEvaluations': value.trueEvaluations,
        'totalEvaluations': value.totalEvaluations,
        'duration': value.duration,
        'timeUnit': value.timeUnit,
    };
}

/**
* @export
* @enum {string}
*/
export enum DampeningModeEnum {
    STRICTCOUNT = 'STRICT_COUNT',
    RELAXEDCOUNT = 'RELAXED_COUNT',
    RELAXEDTIME = 'RELAXED_TIME',
    STRICTTIME = 'STRICT_TIME'
}
/**
* @export
* @enum {string}
*/
export enum DampeningTimeUnitEnum {
    NANOSECONDS = 'NANOSECONDS',
    MICROSECONDS = 'MICROSECONDS',
    MILLISECONDS = 'MILLISECONDS',
    SECONDS = 'SECONDS',
    MINUTES = 'MINUTES',
    HOURS = 'HOURS',
    DAYS = 'DAYS'
}


