/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailProperties
 */
export interface EmailProperties {
    /**
     * 
     * @type {boolean}
     * @memberof EmailProperties
     */
    auth?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmailProperties
     */
    startTlsEnable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmailProperties
     */
    sslTrust?: string;
}

export function EmailPropertiesFromJSON(json: any): EmailProperties {
    return EmailPropertiesFromJSONTyped(json, false);
}

export function EmailPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auth': !exists(json, 'auth') ? undefined : json['auth'],
        'startTlsEnable': !exists(json, 'startTlsEnable') ? undefined : json['startTlsEnable'],
        'sslTrust': !exists(json, 'sslTrust') ? undefined : json['sslTrust'],
    };
}

export function EmailPropertiesToJSON(value?: EmailProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth': value.auth,
        'startTlsEnable': value.startTlsEnable,
        'sslTrust': value.sslTrust,
    };
}


