/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewExternalUserEntity
 */
export interface NewExternalUserEntity {
    /**
     * 
     * @type {string}
     * @memberof NewExternalUserEntity
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof NewExternalUserEntity
     */
    lastname?: string;
    /**
     * 
     * @type {string}
     * @memberof NewExternalUserEntity
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof NewExternalUserEntity
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof NewExternalUserEntity
     */
    picture?: string;
    /**
     * 
     * @type {string}
     * @memberof NewExternalUserEntity
     */
    sourceId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NewExternalUserEntity
     */
    newsletter?: boolean;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof NewExternalUserEntity
     */
    customFields?: { [key: string]: object; };
}

export function NewExternalUserEntityFromJSON(json: any): NewExternalUserEntity {
    return NewExternalUserEntityFromJSONTyped(json, false);
}

export function NewExternalUserEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewExternalUserEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstname': !exists(json, 'firstname') ? undefined : json['firstname'],
        'lastname': !exists(json, 'lastname') ? undefined : json['lastname'],
        'email': json['email'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
        'sourceId': !exists(json, 'sourceId') ? undefined : json['sourceId'],
        'newsletter': !exists(json, 'newsletter') ? undefined : json['newsletter'],
        'customFields': !exists(json, 'customFields') ? undefined : json['customFields'],
    };
}

export function NewExternalUserEntityToJSON(value?: NewExternalUserEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstname': value.firstname,
        'lastname': value.lastname,
        'email': value.email,
        'source': value.source,
        'picture': value.picture,
        'sourceId': value.sourceId,
        'newsletter': value.newsletter,
        'customFields': value.customFields,
    };
}


