/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentityProviderType,
    IdentityProviderTypeFromJSON,
    IdentityProviderTypeFromJSONTyped,
    IdentityProviderTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface SocialIdentityProviderEntity
 */
export interface SocialIdentityProviderEntity {
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    clientId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SocialIdentityProviderEntity
     */
    emailRequired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SocialIdentityProviderEntity
     */
    syncMappings?: boolean;
    /**
     * 
     * @type {IdentityProviderType}
     * @memberof SocialIdentityProviderEntity
     */
    type?: IdentityProviderType;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    authorizationEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    display?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SocialIdentityProviderEntity
     */
    optionalUrlParams?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SocialIdentityProviderEntity
     */
    requiredUrlParams?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    tokenIntrospectionEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    userLogoutEndpoint?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SocialIdentityProviderEntity
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SocialIdentityProviderEntity
     */
    scopeDelimiter?: string;
}

export function SocialIdentityProviderEntityFromJSON(json: any): SocialIdentityProviderEntity {
    return SocialIdentityProviderEntityFromJSONTyped(json, false);
}

export function SocialIdentityProviderEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialIdentityProviderEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'clientId': !exists(json, 'clientId') ? undefined : json['clientId'],
        'emailRequired': !exists(json, 'emailRequired') ? undefined : json['emailRequired'],
        'syncMappings': !exists(json, 'syncMappings') ? undefined : json['syncMappings'],
        'type': !exists(json, 'type') ? undefined : IdentityProviderTypeFromJSON(json['type']),
        'color': !exists(json, 'color') ? undefined : json['color'],
        'authorizationEndpoint': !exists(json, 'authorizationEndpoint') ? undefined : json['authorizationEndpoint'],
        'display': !exists(json, 'display') ? undefined : json['display'],
        'optionalUrlParams': !exists(json, 'optionalUrlParams') ? undefined : json['optionalUrlParams'],
        'requiredUrlParams': !exists(json, 'requiredUrlParams') ? undefined : json['requiredUrlParams'],
        'tokenIntrospectionEndpoint': !exists(json, 'tokenIntrospectionEndpoint') ? undefined : json['tokenIntrospectionEndpoint'],
        'userLogoutEndpoint': !exists(json, 'userLogoutEndpoint') ? undefined : json['userLogoutEndpoint'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
        'scopeDelimiter': !exists(json, 'scopeDelimiter') ? undefined : json['scopeDelimiter'],
    };
}

export function SocialIdentityProviderEntityToJSON(value?: SocialIdentityProviderEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'clientId': value.clientId,
        'emailRequired': value.emailRequired,
        'syncMappings': value.syncMappings,
        'type': IdentityProviderTypeToJSON(value.type),
        'color': value.color,
        'authorizationEndpoint': value.authorizationEndpoint,
        'display': value.display,
        'optionalUrlParams': value.optionalUrlParams,
        'requiredUrlParams': value.requiredUrlParams,
        'tokenIntrospectionEndpoint': value.tokenIntrospectionEndpoint,
        'userLogoutEndpoint': value.userLogoutEndpoint,
        'scopes': value.scopes,
        'scopeDelimiter': value.scopeDelimiter,
    };
}


