import { IMonacoRange, IMonacoCompletionItem, MonacoCompletionItemKind, MonacoCompletionItemInsertTextRule } from "../../../gravitee-monaco-wrapper/monaco-facade";

export const cardSuggestions = (range: IMonacoRange, needsOpeningTag: boolean = false): IMonacoCompletionItem[] => {
  const prefix = needsOpeningTag ? '<' : '';
  const suffix = needsOpeningTag ? '>' : '';
  const closingTag = needsOpeningTag ? '</app-card>' : '';
  
  return [
    // Individual attribute suggestions
    {
      label: 'card:title',
      insertText: 'title="${1:Card Title}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card title attribute',
      documentation: 'Sets the title displayed in the card header',
    },
    {
      label: 'card:centered',
      insertText: 'centered="true"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Center card content',
      documentation: 'Centers the card title and content (boolean: true/false)',
    },
    {
      label: 'card:elevation',
      insertText: 'elevation="${1|0,1,2,3,4,5|}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card shadow elevation',
      documentation: 'Sets the shadow elevation level (0-5, 0 = no shadow)',
    },
    {
      label: 'card:backgroundColor',
      insertText: 'backgroundColor="${1:#ffffff}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card background color',
      documentation: 'Sets the background color of the card (CSS color value)',
    },
    {
      label: 'card:borderColor',
      insertText: 'borderColor="${1:transparent}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card border color',
      documentation: 'Sets the border color (default: transparent)',
    },
    {
      label: 'card:borderWidth',
      insertText: 'borderWidth="${1:1px}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card border width',
      documentation: 'Sets the border width (CSS length value)',
    },
    {
      label: 'card:borderRadius',
      insertText: 'borderRadius="${1:8px}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card border radius',
      documentation: 'Sets the border radius for rounded corners (CSS length value)',
    },
    {
      label: 'card:markdownContent',
      insertText: 'markdownContent="${1:Markdown content}"',
      kind: MonacoCompletionItemKind.Property,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Markdown content',
      documentation: 'Sets markdown content to be rendered inside the card',
    },
    // Card-actions attribute suggestions
    {
      label: 'card-actions',
      insertText: prefix + 'card-actions' + suffix + '\n\t${1:Action buttons go here...}\n</card-actions>',
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card actions container',
      documentation: 'Container for action buttons within a card (no attributes available)',
    },
    // Existing snippets with improved documentation
    {
      label: 'card',
      insertText: prefix + 'app-card title="${1:Card Title}"' + suffix + '\n\t${2:Card content goes here...}\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Basic card component',
      documentation: 'Creates a card with title and content\n\nAvailable attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content',
    },
    {
      label: 'card-centered',
      insertText: prefix + 'app-card title="${1:Card Title}" centered="true"' + suffix + '\n\t${2:Card content goes here...}\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Centered card component',
      documentation: 'Creates a card with centered title and content\n\nAvailable attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content',
    },
    {
      label: 'card-with-border',
      insertText: prefix + 'app-card title="${1:Card Title}" borderColor="${2:#e0e0e0}"' + suffix + '\n\t${3:Card content goes here...}\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card with visible border',
      documentation: 'Creates a card with a visible border\n\nAvailable attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content',
    },
    {
      label: 'card-with-actions',
      insertText: prefix + 'app-card title="${1:Card Title}"' + suffix + '\n\t${2:Card content goes here...}\n\t<card-actions>\n\t\t<app-button href="${3:/link1}" text="${4:Action 1}">${4:Action 1}</app-button>\n\t\t<app-button href="${5:/link2}" text="${6:Action 2}" variant="outlined">${6:Action 2}</app-button>\n\t</card-actions>\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card with action buttons',
      documentation: 'Creates a card with title, content, and action buttons\n\nCard attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content\n\nCard-actions: Container for action buttons (no attributes)',
    },
    {
      label: 'card-elevated',
      insertText: prefix + 'app-card title="${1:Card Title}" elevation="${2:3}"' + suffix + '\n\t${3:Card content goes here...}\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card with custom elevation',
      documentation: 'Creates a card with custom shadow elevation\n\nAvailable attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content',
    },
    {
      label: 'card-custom-styled',
      insertText: prefix + 'app-card title="${1:Card Title}" backgroundColor="${2:#f8f9fa}" borderColor="${3:#dee2e6}" borderRadius="${4:12px}" borderWidth="${5:2px}"' + suffix + '\n\t${6:Card content goes here...}\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Custom styled card',
      documentation: 'Creates a card with custom background, border, and border radius\n\nAvailable attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content',
    },
    {
      label: 'card-complete',
      insertText: prefix + 'app-card title="${1:Card Title}" elevation="${2:3}" backgroundColor="${3:#ffffff}" borderColor="${4:#e0e0e0}" borderRadius="${5:8px}"' + suffix + '\n\t${6:Card content goes here...}\n\t<card-actions>\n\t\t<app-button href="${7:/primary}" text="${8:Primary Action}" variant="filled">${8:Primary Action}</app-button>\n\t\t<app-button href="${9:/secondary}" text="${10:Secondary Action}" variant="outlined">${10:Secondary Action}</app-button>\n\t</card-actions>\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Complete card with all options',
      documentation: 'Creates a fully customized card with all styling and action options\n\nAvailable attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content\n\nCard-actions: Container for action buttons (no attributes)',
    },
    {
      label: 'card-external-actions',
      insertText: prefix + 'app-card title="${1:Card Title}"' + suffix + '\n\t${2:Card content goes here...}\n\t<card-actions>\n\t\t<app-button href="${3:https://docs.example.com}" text="${4:View Docs}" type="external" variant="filled">${4:View Docs}</app-button>\n\t\t<app-button href="${5:https://github.com}" text="${6:GitHub}" type="external" variant="outlined">${6:GitHub}</app-button>\n\t</card-actions>\n' + closingTag,
      kind: MonacoCompletionItemKind.Snippet,
      insertTextRules: MonacoCompletionItemInsertTextRule.InsertAsSnippet,
      range,
      detail: 'Card with external action links',
      documentation: 'Creates a card with action buttons that open external links\n\nAvailable attributes:\n• title: Card title\n• centered: Center content (true/false)\n• elevation: Shadow level (0-5)\n• backgroundColor: Background color\n• borderColor: Border color\n• borderWidth: Border width\n• borderRadius: Border radius\n• markdownContent: Markdown content\n\nCard-actions: Container for action buttons (no attributes)',
    },
  ];
}; 