databaseChangeLog:
  - changeSet:
      id: 4.3.0
      author: GraviteeSource Team
      validCheckSum: ANY
      changes:
        # ################
        # License changes
        # ################
        - createTable:
            tableName: ${gravitee_prefix}licenses
            columns:
              - column: {name: reference_id, type: nvarchar(64), constraints: { nullable: false, primaryKey: true, primaryKeyName: "pk_${gravitee_prefix}licenses" } }
              - column: {name: reference_type, type: nvarchar(64), constraints: { nullable: false, primaryKey: true } }
              - column: {name: license, type: nvarchar(256), constraints: { nullable: false } }
              - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
              - column: {name: updated_at, type: timestamp(6), constraints: { nullable: false }, defaultValueComputed: CURRENT_TIMESTAMP(6) }

