/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Request,
    RequestFromJSON,
    RequestFromJSONTyped,
    RequestToJSON,
    Response,
    ResponseFromJSON,
    ResponseFromJSONTyped,
    ResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationRequest
 */
export interface ApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    api?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof ApplicationRequest
     */
    metadata?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    method?: ApplicationRequestMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    plan?: string;
    /**
     * 
     * @type {Request}
     * @memberof ApplicationRequest
     */
    request?: Request;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRequest
     */
    requestContentLength?: number;
    /**
     * 
     * @type {Response}
     * @memberof ApplicationRequest
     */
    response?: Response;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRequest
     */
    responseContentLength?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRequest
     */
    responseTime?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    securityToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    securityType?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRequest
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRequest
     */
    timestamp?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    transactionId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    uri?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRequest
     */
    user?: string;
}

export function ApplicationRequestFromJSON(json: any): ApplicationRequest {
    return ApplicationRequestFromJSONTyped(json, false);
}

export function ApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'api': !exists(json, 'api') ? undefined : json['api'],
        'host': !exists(json, 'host') ? undefined : json['host'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'plan': !exists(json, 'plan') ? undefined : json['plan'],
        'request': !exists(json, 'request') ? undefined : RequestFromJSON(json['request']),
        'requestContentLength': !exists(json, 'requestContentLength') ? undefined : json['requestContentLength'],
        'response': !exists(json, 'response') ? undefined : ResponseFromJSON(json['response']),
        'responseContentLength': !exists(json, 'responseContentLength') ? undefined : json['responseContentLength'],
        'responseTime': !exists(json, 'responseTime') ? undefined : json['responseTime'],
        'securityToken': !exists(json, 'securityToken') ? undefined : json['securityToken'],
        'securityType': !exists(json, 'securityType') ? undefined : json['securityType'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'transactionId': !exists(json, 'transactionId') ? undefined : json['transactionId'],
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ApplicationRequestToJSON(value?: ApplicationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'api': value.api,
        'host': value.host,
        'id': value.id,
        'metadata': value.metadata,
        'method': value.method,
        'path': value.path,
        'plan': value.plan,
        'request': RequestToJSON(value.request),
        'requestContentLength': value.requestContentLength,
        'response': ResponseToJSON(value.response),
        'responseContentLength': value.responseContentLength,
        'responseTime': value.responseTime,
        'securityToken': value.securityToken,
        'securityType': value.securityType,
        'status': value.status,
        'timestamp': value.timestamp,
        'transactionId': value.transactionId,
        'uri': value.uri,
        'user': value.user,
    };
}

/**
* @export
* @enum {string}
*/
export enum ApplicationRequestMethodEnum {
    CONNECT = 'CONNECT',
    DELETE = 'DELETE',
    GET = 'GET',
    HEAD = 'HEAD',
    OPTIONS = 'OPTIONS',
    PATCH = 'PATCH',
    POST = 'POST',
    PUT = 'PUT',
    TRACE = 'TRACE',
    OTHER = 'OTHER'
}


