/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DictionaryType,
    DictionaryTypeFromJSON,
    DictionaryTypeFromJSONTyped,
    DictionaryTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface DictionaryListItem
 */
export interface DictionaryListItem {
    /**
     * 
     * @type {string}
     * @memberof DictionaryListItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DictionaryListItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DictionaryListItem
     */
    description?: string;
    /**
     * 
     * @type {DictionaryType}
     * @memberof DictionaryListItem
     */
    type?: DictionaryType;
    /**
     * 
     * @type {string}
     * @memberof DictionaryListItem
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof DictionaryListItem
     */
    state?: DictionaryListItemStateEnum;
    /**
     * 
     * @type {number}
     * @memberof DictionaryListItem
     */
    properties?: number;
    /**
     * 
     * @type {Date}
     * @memberof DictionaryListItem
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DictionaryListItem
     */
    updated_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DictionaryListItem
     */
    deployed_at?: Date;
}

export function DictionaryListItemFromJSON(json: any): DictionaryListItem {
    return DictionaryListItemFromJSONTyped(json, false);
}

export function DictionaryListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DictionaryListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : DictionaryTypeFromJSON(json['type']),
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'created_at': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updated_at': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'deployed_at': !exists(json, 'deployed_at') ? undefined : (new Date(json['deployed_at'])),
    };
}

export function DictionaryListItemToJSON(value?: DictionaryListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'type': DictionaryTypeToJSON(value.type),
        'provider': value.provider,
        'state': value.state,
        'properties': value.properties,
        'created_at': value.created_at === undefined ? undefined : (value.created_at.toISOString()),
        'updated_at': value.updated_at === undefined ? undefined : (value.updated_at.toISOString()),
        'deployed_at': value.deployed_at === undefined ? undefined : (value.deployed_at.toISOString()),
    };
}

/**
* @export
* @enum {string}
*/
export enum DictionaryListItemStateEnum {
    INITIALIZED = 'INITIALIZED',
    STOPPED = 'STOPPED',
    STOPPING = 'STOPPING',
    STARTED = 'STARTED',
    CLOSED = 'CLOSED'
}


