/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubAuthentication
 */
export interface GithubAuthentication {
    /**
     * 
     * @type {string}
     * @memberof GithubAuthentication
     */
    clientId?: string;
}

export function GithubAuthenticationFromJSON(json: any): GithubAuthentication {
    return GithubAuthenticationFromJSONTyped(json, false);
}

export function GithubAuthenticationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubAuthentication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': !exists(json, 'clientId') ? undefined : json['clientId'],
    };
}

export function GithubAuthenticationToJSON(value?: GithubAuthentication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientId': value.clientId,
    };
}


