/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpProxy
 */
export interface HttpProxy {
    /**
     * 
     * @type {boolean}
     * @memberof HttpProxy
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpProxy
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpProxy
     */
    password?: string;
    /**
     * 
     * @type {number}
     * @memberof HttpProxy
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof HttpProxy
     */
    type?: HttpProxyTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof HttpProxy
     */
    useSystemProxy?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpProxy
     */
    username?: string;
}

export function HttpProxyFromJSON(json: any): HttpProxy {
    return HttpProxyFromJSONTyped(json, false);
}

export function HttpProxyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpProxy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'host': !exists(json, 'host') ? undefined : json['host'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'port': !exists(json, 'port') ? undefined : json['port'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'useSystemProxy': !exists(json, 'useSystemProxy') ? undefined : json['useSystemProxy'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function HttpProxyToJSON(value?: HttpProxy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'host': value.host,
        'password': value.password,
        'port': value.port,
        'type': value.type,
        'useSystemProxy': value.useSystemProxy,
        'username': value.username,
    };
}

/**
* @export
* @enum {string}
*/
export enum HttpProxyTypeEnum {
    HTTP = 'HTTP',
    SOCKS4 = 'SOCKS4',
    SOCKS5 = 'SOCKS5'
}


