/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum IdentityProviderActivationReferenceType {
    ENVIRONMENT = 'ENVIRONMENT',
    ORGANIZATION = 'ORGANIZATION'
}

export function IdentityProviderActivationReferenceTypeFromJSON(json: any): IdentityProviderActivationReferenceType {
    return IdentityProviderActivationReferenceTypeFromJSONTyped(json, false);
}

export function IdentityProviderActivationReferenceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityProviderActivationReferenceType {
    return json as IdentityProviderActivationReferenceType;
}

export function IdentityProviderActivationReferenceTypeToJSON(value?: IdentityProviderActivationReferenceType | null): any {
    return value as any;
}

