/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JupiterMode
 */
export interface JupiterMode {
    /**
     * 
     * @type {boolean}
     * @memberof JupiterMode
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JupiterMode
     */
    isDefault?: string;
}

export function JupiterModeFromJSON(json: any): JupiterMode {
    return JupiterModeFromJSONTyped(json, false);
}

export function JupiterModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JupiterMode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'isDefault': !exists(json, 'isDefault') ? undefined : json['isDefault'],
    };
}

export function JupiterModeToJSON(value?: JupiterMode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'isDefault': value.isDefault,
    };
}


