/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
     ListenerHttpV4FromJSONTyped,
     ListenerSubscriptionV4FromJSONTyped,
     ListenerTcpV4FromJSONTyped
} from './';

/**
 * A list of listeners used to describe our you api could be reached.
 * @export
 * @interface ListenerV4
 */
export interface ListenerV4 {
    /**
     * 
     * @type {string}
     * @memberof ListenerV4
     */
    type: ListenerV4TypeEnum;
}

export function ListenerV4FromJSON(json: any): ListenerV4 {
    return ListenerV4FromJSONTyped(json, false);
}

export function ListenerV4FromJSONTyped(json: any, ignoreDiscriminator: boolean): ListenerV4 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'ListenerHttpV4') {
            return ListenerHttpV4FromJSONTyped(json, true);
        }
        if (json['type'] === 'ListenerSubscriptionV4') {
            return ListenerSubscriptionV4FromJSONTyped(json, true);
        }
        if (json['type'] === 'ListenerTcpV4') {
            return ListenerTcpV4FromJSONTyped(json, true);
        }
    }
    return {
        
        'type': json['type'],
    };
}

export function ListenerV4ToJSON(value?: ListenerV4 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

/**
* @export
* @enum {string}
*/
export enum ListenerV4TypeEnum {
    HTTP = 'HTTP',
    SUBSCRIPTION = 'SUBSCRIPTION',
    TCP = 'TCP'
}


