/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MembershipListItem
 */
export interface MembershipListItem {
    /**
     * 
     * @type {string}
     * @memberof MembershipListItem
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipListItem
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipListItem
     */
    id?: string;
}

export function MembershipListItemFromJSON(json: any): MembershipListItem {
    return MembershipListItemFromJSONTyped(json, false);
}

export function MembershipListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : json['role'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function MembershipListItemToJSON(value?: MembershipListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
        'displayName': value.displayName,
        'id': value.id,
    };
}


