/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DashboardReferenceType,
    DashboardReferenceTypeFromJSON,
    DashboardReferenceTypeFromJSONTyped,
    DashboardReferenceTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewDashboardEntity
 */
export interface NewDashboardEntity {
    /**
     * 
     * @type {string}
     * @memberof NewDashboardEntity
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof NewDashboardEntity
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NewDashboardEntity
     */
    definition?: string;
    /**
     * 
     * @type {DashboardReferenceType}
     * @memberof NewDashboardEntity
     */
    reference_type: DashboardReferenceType;
    /**
     * 
     * @type {string}
     * @memberof NewDashboardEntity
     */
    reference_id: string;
    /**
     * 
     * @type {string}
     * @memberof NewDashboardEntity
     */
    query_filter?: string;
}

export function NewDashboardEntityFromJSON(json: any): NewDashboardEntity {
    return NewDashboardEntityFromJSONTyped(json, false);
}

export function NewDashboardEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewDashboardEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'definition': !exists(json, 'definition') ? undefined : json['definition'],
        'reference_type': DashboardReferenceTypeFromJSON(json['reference_type']),
        'reference_id': json['reference_id'],
        'query_filter': !exists(json, 'query_filter') ? undefined : json['query_filter'],
    };
}

export function NewDashboardEntityToJSON(value?: NewDashboardEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'enabled': value.enabled,
        'definition': value.definition,
        'reference_type': DashboardReferenceTypeToJSON(value.reference_type),
        'reference_id': value.reference_id,
        'query_filter': value.query_filter,
    };
}


