/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * Some news resources are in alpha version. This implies that they are likely to be modified or even removed in future versions. They are marked with the 🧪 symbol
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { KeyStore } from './KeyStore';
import {
    KeyStoreFromJSON,
    KeyStoreFromJSONTyped,
    KeyStoreToJSON,
} from './KeyStore';

/**
 * 
 * @export
 * @interface NoneKeyStore
 */
export interface NoneKeyStore extends KeyStore {
}



/**
 * Check if a given object implements the NoneKeyStore interface.
 */
export function instanceOfNoneKeyStore(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NoneKeyStoreFromJSON(json: any): NoneKeyStore {
    return NoneKeyStoreFromJSONTyped(json, false);
}

export function NoneKeyStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoneKeyStore {
    return json;
}

export function NoneKeyStoreToJSON(value?: NoneKeyStore | null): any {
    return value;
}

