/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * Some news resources are in alpha version. This implies that they are likely to be modified or even removed in future versions. They are marked with the 🧪 symbol
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NotificationTemplateType = {
    EMAIL: 'EMAIL',
    PORTAL: 'PORTAL'
} as const;
export type NotificationTemplateType = typeof NotificationTemplateType[keyof typeof NotificationTemplateType];


export function NotificationTemplateTypeFromJSON(json: any): NotificationTemplateType {
    return NotificationTemplateTypeFromJSONTyped(json, false);
}

export function NotificationTemplateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationTemplateType {
    return json as NotificationTemplateType;
}

export function NotificationTemplateTypeToJSON(value?: NotificationTemplateType | null): any {
    return value as any;
}

