/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * Some news resources are in alpha version. This implies that they are likely to be modified or even removed in future versions. They are marked with the 🧪 symbol
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NotificationConfigType = {
    PORTAL: 'PORTAL',
    GENERIC: 'GENERIC'
} as const;
export type NotificationConfigType = typeof NotificationConfigType[keyof typeof NotificationConfigType];


export function NotificationConfigTypeFromJSON(json: any): NotificationConfigType {
    return NotificationConfigTypeFromJSONTyped(json, false);
}

export function NotificationConfigTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationConfigType {
    return json as NotificationConfigType;
}

export function NotificationConfigTypeToJSON(value?: NotificationConfigType | null): any {
    return value as any;
}

