/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotifierListItem
 */
export interface NotifierListItem {
    /**
     * 
     * @type {string}
     * @memberof NotifierListItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof NotifierListItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof NotifierListItem
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NotifierListItem
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof NotifierListItem
     */
    schema?: string;
}

export function NotifierListItemFromJSON(json: any): NotifierListItem {
    return NotifierListItemFromJSONTyped(json, false);
}

export function NotifierListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotifierListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'schema': !exists(json, 'schema') ? undefined : json['schema'],
    };
}

export function NotifierListItemToJSON(value?: NotifierListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'version': value.version,
        'schema': value.schema,
    };
}


