/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * Some news resources are in alpha version. This implies that they are likely to be modified or even removed in future versions. They are marked with the 🧪 symbol
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlanStatus = {
    STAGING: 'STAGING',
    PUBLISHED: 'PUBLISHED',
    CLOSED: 'CLOSED',
    DEPRECATED: 'DEPRECATED'
} as const;
export type PlanStatus = typeof PlanStatus[keyof typeof PlanStatus];


export function PlanStatusFromJSON(json: any): PlanStatus {
    return PlanStatusFromJSONTyped(json, false);
}

export function PlanStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanStatus {
    return json as PlanStatus;
}

export function PlanStatusToJSON(value?: PlanStatus | null): any {
    return value as any;
}

