/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * Some news resources are in alpha version. This implies that they are likely to be modified or even removed in future versions. They are marked with the 🧪 symbol
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Enabled } from './Enabled';
import {
    EnabledFromJSON,
    EnabledFromJSONTyped,
    EnabledToJSON,
} from './Enabled';
import type { GithubAuthentication } from './GithubAuthentication';
import {
    GithubAuthenticationFromJSON,
    GithubAuthenticationFromJSONTyped,
    GithubAuthenticationToJSON,
} from './GithubAuthentication';
import type { GoogleAuthentication } from './GoogleAuthentication';
import {
    GoogleAuthenticationFromJSON,
    GoogleAuthenticationFromJSONTyped,
    GoogleAuthenticationToJSON,
} from './GoogleAuthentication';
import type { OAuth2Authentication } from './OAuth2Authentication';
import {
    OAuth2AuthenticationFromJSON,
    OAuth2AuthenticationFromJSONTyped,
    OAuth2AuthenticationToJSON,
} from './OAuth2Authentication';

/**
 * 
 * @export
 * @interface PortalAuthentication
 */
export interface PortalAuthentication {
    /**
     * 
     * @type {Enabled}
     * @memberof PortalAuthentication
     */
    forceLogin?: Enabled;
    /**
     * 
     * @type {GithubAuthentication}
     * @memberof PortalAuthentication
     */
    github?: GithubAuthentication;
    /**
     * 
     * @type {GoogleAuthentication}
     * @memberof PortalAuthentication
     */
    google?: GoogleAuthentication;
    /**
     * 
     * @type {Enabled}
     * @memberof PortalAuthentication
     */
    localLogin?: Enabled;
    /**
     * 
     * @type {OAuth2Authentication}
     * @memberof PortalAuthentication
     */
    oauth2?: OAuth2Authentication;
}

/**
 * Check if a given object implements the PortalAuthentication interface.
 */
export function instanceOfPortalAuthentication(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PortalAuthenticationFromJSON(json: any): PortalAuthentication {
    return PortalAuthenticationFromJSONTyped(json, false);
}

export function PortalAuthenticationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortalAuthentication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forceLogin': !exists(json, 'forceLogin') ? undefined : EnabledFromJSON(json['forceLogin']),
        'github': !exists(json, 'github') ? undefined : GithubAuthenticationFromJSON(json['github']),
        'google': !exists(json, 'google') ? undefined : GoogleAuthenticationFromJSON(json['google']),
        'localLogin': !exists(json, 'localLogin') ? undefined : EnabledFromJSON(json['localLogin']),
        'oauth2': !exists(json, 'oauth2') ? undefined : OAuth2AuthenticationFromJSON(json['oauth2']),
    };
}

export function PortalAuthenticationToJSON(value?: PortalAuthentication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forceLogin': EnabledToJSON(value.forceLogin),
        'github': GithubAuthenticationToJSON(value.github),
        'google': GoogleAuthenticationToJSON(value.google),
        'localLogin': EnabledToJSON(value.localLogin),
        'oauth2': OAuth2AuthenticationToJSON(value.oauth2),
    };
}

