/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * Some news resources are in alpha version. This implies that they are likely to be modified or even removed in future versions. They are marked with the 🧪 symbol
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingAnswerEntity
 */
export interface RatingAnswerEntity {
    /**
     * 
     * @type {string}
     * @memberof RatingAnswerEntity
     */
    comment?: string;
    /**
     * 
     * @type {Date}
     * @memberof RatingAnswerEntity
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof RatingAnswerEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RatingAnswerEntity
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof RatingAnswerEntity
     */
    userDisplayName?: string;
}

/**
 * Check if a given object implements the RatingAnswerEntity interface.
 */
export function instanceOfRatingAnswerEntity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatingAnswerEntityFromJSON(json: any): RatingAnswerEntity {
    return RatingAnswerEntityFromJSONTyped(json, false);
}

export function RatingAnswerEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingAnswerEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'userDisplayName': !exists(json, 'userDisplayName') ? undefined : json['userDisplayName'],
    };
}

export function RatingAnswerEntityToJSON(value?: RatingAnswerEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'id': value.id,
        'user': value.user,
        'userDisplayName': value.userDisplayName,
    };
}

