/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenEntity
 */
export interface TokenEntity {
    /**
     * 
     * @type {Date}
     * @memberof TokenEntity
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TokenEntity
     */
    expires_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof TokenEntity
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof TokenEntity
     */
    last_use_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof TokenEntity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenEntity
     */
    token?: string;
}

export function TokenEntityFromJSON(json: any): TokenEntity {
    return TokenEntityFromJSONTyped(json, false);
}

export function TokenEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created_at': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'expires_at': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'last_use_at': !exists(json, 'last_use_at') ? undefined : (new Date(json['last_use_at'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function TokenEntityToJSON(value?: TokenEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.created_at === undefined ? undefined : (value.created_at.toISOString()),
        'expires_at': value.expires_at === undefined ? undefined : (value.expires_at.toISOString()),
        'id': value.id,
        'last_use_at': value.last_use_at === undefined ? undefined : (value.last_use_at.toISOString()),
        'name': value.name,
        'token': value.token,
    };
}


