/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopApiEntity
 */
export interface TopApiEntity {
    /**
     * 
     * @type {string}
     * @memberof TopApiEntity
     */
    api?: string;
    /**
     * 
     * @type {string}
     * @memberof TopApiEntity
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TopApiEntity
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TopApiEntity
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof TopApiEntity
     */
    picture_url?: string;
    /**
     * 
     * @type {string}
     * @memberof TopApiEntity
     */
    version?: string;
}

export function TopApiEntityFromJSON(json: any): TopApiEntity {
    return TopApiEntityFromJSONTyped(json, false);
}

export function TopApiEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopApiEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'api': !exists(json, 'api') ? undefined : json['api'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'picture_url': !exists(json, 'picture_url') ? undefined : json['picture_url'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function TopApiEntityToJSON(value?: TopApiEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'api': value.api,
        'description': value.description,
        'name': value.name,
        'order': value.order,
        'picture_url': value.picture_url,
        'version': value.version,
    };
}


