db.apis.createIndex( { "visibility" : 1 } );
db.apis.createIndex( { "group" : 1 } );
db.applications.createIndex( { "group" : 1 } );
db.applications.createIndex( { "name" : 1 } );
db.events.createIndex( { "type" : 1 } );
db.events.createIndex( { "updatedAt" : 1 } );
db.events.createIndex( { "properties.api_id" : 1 } );
db.plans.createIndex( { "apis" : 1 } );
db.subscriptions.createIndex( { "plan" : 1 } );
db.subscriptions.createIndex( { "application" : 1 } );
db.keys.createIndex( { "plan" : 1 } );
db.keys.createIndex( { "application" : 1 } );
db.keys.createIndex( { "updatedAt" : 1 } );
db.keys.createIndex( { "revoked" : 1 } );
db.keys.createIndex( { "plan" : 1 , "revoked" : 1, "updatedAt" : 1 } );
db.pages.createIndex( { "api" : 1 } );
db.memberships.createIndex( {"_id.referenceType":1, "_id.referenceId":1, "type":1} );
db.memberships.createIndex( {"_id.referenceType":1, "_id.userId":1} );
db.memberships.createIndex( {"_id.referenceType":1, "_id.userId":1, "type":1} );
db.memberships.createIndex( {"_id.referenceType":1, "_id.referenceId":1, "roles":1} );
db.roles.createIndex( {"_id.scope": 1 } );
db.rating.createIndex( { "api" : 1 } );
db.ratingAnswers.createIndex( { "rating" : 1 } );

db.apis.reIndex();
db.applications.reIndex();
db.events.reIndex();
db.plans.reIndex();
db.subscriptions.reIndex();
db.keys.reIndex();
db.pages.reIndex();
db.memberships.reIndex();
db.roles.reIndex();
db.rating.reIndex();
db.ratingAnswers.reIndex();