title: |
  [${application.name}] Subscription Rejected
message: |
  The subscription request to the plan "${plan.name}" 
  of the <#if api??>api "${api.name}"<#elseif apiProduct??>API Product "${apiProduct.name}"<#else>api/product</#if> was rejected.