# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Trigger GKO env rollout

on:
  push:
    branches:
      - master
      - /^[0-9]+\.[0-9]+\.x$/
jobs:
  trigger-gko-dev-rollout:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger rollout on GKO environment"
        run: |
          export JSON_PAYLOAD="{ \"branch\": \"${TARGET_BRANCH}\", \"parameters\": { \"trigger\": \"rollout-apim\", \"apim-commit-hash\": \"${COMMIT_HASH}\", \"apim-source-branch\": \"${GITHUB_REF##*/}\" } }"
          
          curl -X POST -d "${JSON_PAYLOAD}" \
            -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token: ${CCI_TOKEN}" \
            https://circleci.com/api/v2/project/gh/${ORG_NAME}/${REPO_NAME}/pipeline | jq .

        env:
          ORG_NAME: gravitee-io
          REPO_NAME: gravitee-kubernetes-operator
          COMMIT_HASH: ${{ github.sha }}
          TARGET_BRANCH: master
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
